CREATE OR REPLACE  FUNCTION SC_CREDIT.FN_SEL_LOAN_BALANCE_DET_JSON (
   PA_LOAN_ID                IN SC_CREDIT.TA_LOAN_BALANCE.FI_LOAN_ID%TYPE
   ,PA_ADMIN_CENTER_ID       IN SC_CREDIT.TA_LOAN_BALANCE.FI_ADMIN_CENTER_ID%TYPE
   ,PA_BALANCE_SEQ           IN SC_CREDIT.TA_LOAN_BALANCE.FI_BALANCE_SEQ%TYPE
   ,PA_UUID_TRACKING         IN SC_CREDIT.TA_LOAN.FC_UUID_TRACKING%TYPE)
RETURN CLOB IS
   /* **************************************************************
   * PROJECT: PURPOSE CORE
   * DESCRIPTION: SELECT BALANCE DETAIL AND CONVERT TO JSON
   * CREATED DATE: 12/11/2024
   * CREATOR: LUIS RAMIREZ
   * MODIFICATION DATE: 26/12/2024
   * PERFORMANCE MODIFICATIONS - LUIS RAMIREZ
   ************************************************************** */
   CSL_0                     CONSTANT SIMPLE_INTEGER := 0;
   CSL_1                     CONSTANT SIMPLE_INTEGER := 1;
   CSL_FN                    CONSTANT SIMPLE_INTEGER := 1;
   VL_JSON                   CLOB := NULL;

BEGIN

   SELECT JSON_ARRAYAGG(
             JSON_OBJECT(
                KEY 'conceptId' VALUE DET.FI_LOAN_CONCEPT_ID,
                KEY 'itemAmount' VALUE DET.FN_ITEM_AMOUNT
             )
          ) AS JSON_ARRAY
   INTO
      VL_JSON
   FROM SC_CREDIT.TA_LOAN_BALANCE BA
      INNER JOIN SC_CREDIT.TA_LOAN_BALANCE_DETAIL DET
              ON DET.FI_LOAN_ID = BA.FI_LOAN_ID
             AND DET.FI_ADMIN_CENTER_ID = BA.FI_ADMIN_CENTER_ID
             AND DET.FI_LOAN_BALANCE_ID = BA.FI_LOAN_BALANCE_ID
             AND DET.FI_LOAN_CONCEPT_ID >= CSL_0
   WHERE BA.FI_ADMIN_CENTER_ID = PA_ADMIN_CENTER_ID
     AND BA.FI_LOAN_ID = PA_LOAN_ID
     AND BA.FI_BALANCE_SEQ = PA_BALANCE_SEQ;

   RETURN VL_JSON;

EXCEPTION
   WHEN NO_DATA_FOUND THEN
      SC_CREDIT.SP_ERROR_LOG(
         UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_FN)
         ,SQLCODE
         ,SQLERRM
         ,DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
         ,PA_UUID_TRACKING
         ,NULL
         );
      RETURN NULL;
   WHEN OTHERS THEN
      SC_CREDIT.SP_ERROR_LOG(
         UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_FN)
         ,SQLCODE
         ,SQLERRM
         ,DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
         ,PA_UUID_TRACKING
         ,NULL
         );
      RETURN NULL;
END FN_SEL_LOAN_BALANCE_DET_JSON;

/

GRANT EXECUTE ON SC_CREDIT.FN_SEL_LOAN_BALANCE_DET_JSON TO USRNCPCREDIT1
/
GRANT EXECUTE ON SC_CREDIT.FN_SEL_LOAN_BALANCE_DET_JSON TO USRBTCCREDIT1
/
