CREATE OR REPLACE  TYPE SC_CREDIT.TYP_REC_BTC_DETAIL AS OBJECT ( FI_ADMIN_CENTER_ID       NUMBER(8,0), FI_LOAN_ID               NUMBER(15,0), FI_LOAN_OPERATION_ID     NUMBER(15,0), FI_LOAN_CONCEPT_ID       NUMBER(5,0), FN_ITEM_AMOUNT           NUMBER(12,2)
); 
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_DETAIL TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_DETAIL TO USRBTCCREDIT1;
