CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_SYNC_PAYMENT_SCHEDULE_STATUS (
    PA_SYNC_JSON   		  CLOB,
    PA_UPDATED_ROWS	OUT NUMBER,
    PA_STATUS_CODE	OUT NUMBER,
    PA_STATUS_MSG 	OUT VARCHAR2
  ) IS
/* **************************************************************
* PROJECT: NCP
* DESCRIPTION: CATALOG SYNCHONIZATION TC_PAYMENT_SCHEDULE_STATUS
* CREATED DATE: 2025/01/09
* CREATOR: CESAR CORTES
* MODIFICATION DATE: 2025/01/09
************************************************************** */
  BEGIN
    PA_STATUS_CODE := 0;
    PA_STATUS_MSG  := 'OK';

  MERGE INTO SC_CREDIT.TC_PAYMENT_SCHEDULE_STATUS A
  USING (
    SELECT
      *
    FROM
      JSON_TABLE ( PA_SYNC_JSON, '$.paymentScheduleStatus[*]'
        COLUMNS (
          ID NUMBER PATH '$.id',
          DESCRIPTION VARCHAR2 ( 80 ) PATH '$.description',
          STATUS NUMBER PATH '$.status',
          USER_TYPE VARCHAR2 ( 30 )  PATH '$.user',
          CREATED_DATE TIMESTAMP PATH '$.createdDate',
          MODIFICATION_DATE TIMESTAMP PATH '$.modificationDate'
        )
      )
  ) B ON ( A.FI_PMT_SCHEDULE_STATUS_ID = B.ID )
  WHEN MATCHED THEN UPDATE
  SET A.FI_PMT_SCHEDULE_STATUS_DESC = B.DESCRIPTION,
      A.FI_STATUS = B.STATUS,
      A.FC_USER = B.USER_TYPE,
      A.FD_MODIFICATION_DATE = CAST(B.MODIFICATION_DATE AS DATE)
  WHEN NOT MATCHED THEN
  INSERT (
    FI_PMT_SCHEDULE_STATUS_ID,
    FI_PMT_SCHEDULE_STATUS_DESC,
    FI_STATUS,
    FC_USER,
    FD_CREATED_DATE,
    FD_MODIFICATION_DATE)
  VALUES
    ( B.ID,
      B.DESCRIPTION,
      B.STATUS,
      B.USER_TYPE,
      B.CREATED_DATE,
      B.MODIFICATION_DATE);

      PA_UPDATED_ROWS := SQL%ROWCOUNT;

  COMMIT;

  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      PA_STATUS_CODE := SQLCODE;
      PA_STATUS_MSG  := SQLERRM;
      SC_CREDIT.SP_ERROR_LOG('SP_SYNC_PAYMENT_SCHEDULE_STATUS', SQLCODE, SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, NULL,'');

  END SP_SYNC_PAYMENT_SCHEDULE_STATUS;

/

GRANT EXECUTE ON SC_CREDIT.SP_SYNC_PAYMENT_SCHEDULE_STATUS TO USRPURPOSEWS
/
GRANT EXECUTE ON SC_CREDIT.SP_SYNC_PAYMENT_SCHEDULE_STATUS TO USRNCPCREDIT1
/
