CREATE OR REPLACE  TYPE SC_CREDIT.TYP_TAB_BTC_ERROR AS TABLE OF SC_CREDIT.TYP_REC_BTC_ERROR; 
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_ERROR TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_ERROR TO USRBTCCREDIT1;
