CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_BTC_UPD_LOAN_STATUS_DETAIL 
   (PA_LOAN_ID                    IN NUMBER
   ,PA_ADMIN_CENTER_ID            IN NUMBER
   ,PA_PAYMENT_NUMBER_ID          IN NUMBER
   ,PA_COUNTER_DAY                IN NUMBER
   ,PA_ON_OFF                     IN NUMBER
   ,PA_TRANSACTION                IN NUMBER
   ,PA_BAN_OPERATION              IN NUMBER
   ,PA_COMMIT                     IN NUMBER
   ,PA_STATUS_CODE                OUT NUMBER
   ,PA_STATUS_MSG                 OUT VARCHAR2
   )
   IS
     /* **************************************************************
   * DESCRIPTION: PROCESS TO INSERT IN TABLE INTEREST
   * CREATED DATE: 08/11/2024
   * CREATOR: CRISTHIAN MORALES
   ************************************************************** */

  CSL_0                         CONSTANT SIMPLE_INTEGER := 0;
  CSL_1                         CONSTANT SIMPLE_INTEGER := 1;
  CSL_SP                        CONSTANT SIMPLE_INTEGER := 1;
  CSL_2002                      CONSTANT SIMPLE_INTEGER := -20002;
  CSL_ARROW                     CONSTANT VARCHAR2(20)   := '->';
  CSL_MSG_SUCCESS               CONSTANT VARCHAR2(20)   := 'SUCCESS';
  CSL_NOT_UPDATED               CONSTANT VARCHAR2(20)   := ' NOT_UPDATE ';
  CSL_LOAN_ID                   CONSTANT VARCHAR2(20)   := 'LOAN_ID';
  CSL_TA_LOAN_STATUS_DETAIL     CONSTANT VARCHAR2(20)   := ' LOAN_STATUS_DETAIL ';
  CSL_ADMIN_CENTER_ID           CONSTANT VARCHAR2(20)   := 'ADMIN_CENTER_ID';
  CSL_NULL                      CONSTANT VARCHAR2(20)   := ' PARAMETERS NULL ';
  CSL_COMA                      CONSTANT VARCHAR2(20)   := ',';
  CSL_DAY                       DATE:= SYSDATE;


  BEGIN

     PA_STATUS_CODE :=CSL_0;
     PA_STATUS_MSG  :=CSL_MSG_SUCCESS;

     IF PA_BAN_OPERATION=CSL_1 THEN
         UPDATE SC_CREDIT.TA_LOAN_STATUS_DETAIL LD
              SET LD.FI_COUNTER_DAY=NVL(PA_COUNTER_DAY,LD.FI_COUNTER_DAY)
                 ,LD.FI_ON_OFF=NVL(PA_ON_OFF,LD.FI_ON_OFF)
                 ,LD.FD_MODIFICATION_DATE=CSL_DAY
            WHERE LD.FI_LOAN_ID=PA_LOAN_ID
            AND   LD.FI_ADMIN_CENTER_ID=PA_ADMIN_CENTER_ID
            AND   LD.FI_PAYMENT_NUMBER_ID=PA_PAYMENT_NUMBER_ID
            AND   LD.FI_ON_OFF=CSL_1;
     ELSIF PA_BAN_OPERATION=CSL_0 THEN
         UPDATE SC_CREDIT.TA_LOAN_STATUS_DETAIL LD
              SET LD.FI_COUNTER_DAY=NVL(PA_COUNTER_DAY,FI_COUNTER_DAY)
                 ,LD.FI_ON_OFF=NVL(PA_ON_OFF,FI_ON_OFF)
                 ,LD.FD_MODIFICATION_DATE=CSL_DAY
            WHERE LD.FI_LOAN_ID=PA_LOAN_ID
            AND   LD.FI_ADMIN_CENTER_ID=PA_ADMIN_CENTER_ID
            AND   LD.FI_ON_OFF=CSL_1;
      END IF;

        IF SQL%ROWCOUNT = CSL_0 THEN
         RAISE_APPLICATION_ERROR(CSL_2002, CSL_NOT_UPDATED || CSL_TA_LOAN_STATUS_DETAIL);
        END IF;

         IF PA_COMMIT = CSL_1 THEN
         COMMIT;
         END IF;

        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        PA_STATUS_CODE := SQLCODE;
        PA_STATUS_MSG := SQLERRM || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;

        SC_CREDIT.SP_BATCH_ERROR_LOG(UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_SP)
                                    ,SQLCODE
                                    ,SQLERRM
                                    ,DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
                                    ,PA_TRANSACTION
                                    ,NULL
                                    ||CSL_ADMIN_CENTER_ID ||PA_ADMIN_CENTER_ID);
  END SP_BTC_UPD_LOAN_STATUS_DETAIL;

/

GRANT EXECUTE ON SC_CREDIT.SP_BTC_UPD_LOAN_STATUS_DETAIL TO USRNCPCREDIT1
/
GRANT EXECUTE ON SC_CREDIT.SP_BTC_UPD_LOAN_STATUS_DETAIL TO USRBTCCREDIT1
/
