CREATE OR REPLACE  TYPE SC_CREDIT.TYP_TAB_BTC_STATUS AS TABLE OF SC_CREDIT.TYP_REC_BTC_STATUS; 
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_STATUS TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_STATUS TO USRBTCCREDIT1;
