CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_BTC_INS_LOAN_STATUS 
  (
    PA_LOAN_ID                IN  NUMBER
   ,PA_ADMIN_CENTER_ID        IN  NUMBER
   ,PA_LOAN_OPERATION_ID      IN  NUMBER
   ,PA_LOAN_STATUS_ID         IN  NUMBER
   ,PA_LOAN_STATUS_OLD_ID     IN  NUMBER
   ,PA_TRIGGER_ID             IN  NUMBER
   ,PA_LOAN_STATUS_DATE       IN  VARCHAR2
   ,PA_COMMIT                 IN  NUMBER
   ,PA_TRANSACTION         IN  NUMBER
   ,PA_STATUS_CODE            OUT NUMBER
   ,PA_STATUS_MSG             OUT VARCHAR2
   )
   IS
   /* **************************************************************
   * DESCRIPTION: PROCESS TO INSERT IN TABLE TA_LOAN_STATUS
   * CREATED DATE: 12/11/2024
   * CREATOR: CRISTHIAN MORALES
   ************************************************************** */
   CSL_0                 CONSTANT SIMPLE_INTEGER := 0;
   CSL_1                 CONSTANT SIMPLE_INTEGER := 1;
   CSL_SP                CONSTANT SIMPLE_INTEGER := 1;
   CSL_2002              CONSTANT SIMPLE_INTEGER := -20002;
   CSL_DATE_FORMAT       CONSTANT VARCHAR2(40)   := 'MM/DD/YYYY hh24:mi:ss';
   CSL_MSG_SUCCESS        CONSTANT VARCHAR2(20)   := 'SUCCESS';
   CSL_ARROW             CONSTANT VARCHAR2(5)    := '->';
   CSL_TA_LOAN_STATUS    CONSTANT VARCHAR2(20)   := ' LOAN_STATUS_DETAIL';
   CSL_NOT_INSERT        CONSTANT VARCHAR2(50)   := 'NOT_INSERT';
   CSL_ADMIN_CENTER_ID   CONSTANT VARCHAR2(20)   := 'ADMIN_CENTER_ID';

   BEGIN

     PA_STATUS_CODE:= CSL_0;
     PA_STATUS_MSG:=CSL_MSG_SUCCESS;

   INSERT INTO SC_CREDIT.TA_LOAN_STATUS
             (FI_LOAN_ID
             ,FI_ADMIN_CENTER_ID
             ,FI_LOAN_OPERATION_ID
             ,FI_LOAN_STATUS_ID
             ,FI_LOAN_STATUS_OLD_ID
             ,FI_TRIGGER_ID
             ,FD_LOAN_STATUS_DATE
             ,FC_USER
             ,FD_CREATED_DATE
             ,FD_MODIFICATION_DATE
             )
       VALUES(PA_LOAN_ID
             ,PA_ADMIN_CENTER_ID
             ,PA_LOAN_OPERATION_ID
             ,PA_LOAN_STATUS_ID
             ,PA_LOAN_STATUS_OLD_ID
             ,PA_TRIGGER_ID
             ,TO_DATE(PA_LOAN_STATUS_DATE,CSL_DATE_FORMAT)
             ,USER
             ,SYSDATE
             ,SYSDATE
             );

   IF SQL%ROWCOUNT = CSL_0 THEN
      RAISE_APPLICATION_ERROR(CSL_2002, CSL_TA_LOAN_STATUS || CSL_NOT_INSERT);
   END IF;

   IF PA_COMMIT = CSL_1 THEN
     COMMIT;
   END IF;

      --EXCEPTION HANDLING
   EXCEPTION
      WHEN OTHERS THEN
      ROLLBACK;
      PA_STATUS_CODE := SQLCODE;
      PA_STATUS_MSG := SQLERRM || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;

      SC_CREDIT.SP_BATCH_ERROR_LOG(UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_SP)
                                  ,SQLCODE
                                  ,SQLERRM
                                  ,DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
                                  ,PA_TRANSACTION
                                  ,NULL
                                  ||CSL_ADMIN_CENTER_ID ||PA_ADMIN_CENTER_ID);

  END SP_BTC_INS_LOAN_STATUS;

/

GRANT EXECUTE ON SC_CREDIT.SP_BTC_INS_LOAN_STATUS TO USRNCPCREDIT1
/
GRANT EXECUTE ON SC_CREDIT.SP_BTC_INS_LOAN_STATUS TO USRBTCCREDIT1
/
