CREATE OR REPLACE  TYPE SC_CREDIT.TYP_TAB_BTC_STATUS_DETAIL AS TABLE OF SC_CREDIT.TYP_REC_BTC_STATUS_DETAIL; 
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_STATUS_DETAIL TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_STATUS_DETAIL TO USRBTCCREDIT1;
