CREATE OR REPLACE  TYPE SC_CREDIT.TYP_REC_LOAN_OP_TENDER AS OBJECT ( FI_TENDER_TYPE_ID   NUMBER (4,0), FN_OPERATION_AMOUNT NUMBER(12,2)
); 
GRANT EXECUTE ON SC_CREDIT.TYP_REC_LOAN_OP_TENDER TO USRNCPCREDIT1;
