CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_INS_LOAN_OPERATION_CLEAR (
    PA_LOAN_ID            IN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FI_LOAN_ID%TYPE,
    PA_ADMIN_CENTER_ID    IN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FI_ADMIN_CENTER_ID%TYPE,
    PA_OPERATION_CLEAR_ID IN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FI_OPERATION_CLEAR_ID%TYPE,
    PA_OPERATION_REF_ID   IN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FI_OPERATION_REF_ID%TYPE,
    PA_USER               IN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FC_USER%TYPE,
    PA_IP_ADDRESS         IN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FC_IP_ADDRESS%TYPE,
    PA_UUID_TRACKING      IN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FC_UUID_TRACKING%TYPE,
    PA_STATUS_CODE        OUT NUMBER,
    PA_STATUS_MSG         OUT VARCHAR2
)
IS
 /* *************************************************************************
 * PROJECT: CORE LOAN
 * DESCRIPTION: PROCEDURE FOR SAVING INFORMATION REGARDING AN OPERATION
 *              WHICH IS CLEARED.
 * PRECONDITIONS: PRE-EXISTING LOANS AND OPERATIONS
 * CREATED DATE: 07/01/2025
 * CREATOR: GILBERTO CHAVEZ MUNOZ
 ****************************************************************************/
  CSL_0            CONSTANT SIMPLE_INTEGER := 0;
  CSL_1            CONSTANT SIMPLE_INTEGER := 1;
  CSL_204          CONSTANT SIMPLE_INTEGER := 204;
  CSL_ARROW        CONSTANT VARCHAR2(5)  := '->';
  CSL_JSON         CONSTANT VARCHAR2(5)  := NULL;
  CSL_SUCCESS      CONSTANT VARCHAR2(8)  := 'SUCCESS';
  CSL_NO_INSERTION CONSTANT VARCHAR2(20) := 'NO DATA INSERTED';
  CSL_SP           CONSTANT SIMPLE_INTEGER := 1;
  VG_LOAN_OPERATION_VOID_ID SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_LOAN_OPERATION_VOID_ID%TYPE;

BEGIN
INSERT INTO SC_CREDIT.TA_LOAN_OPERATION_CLEAR(
    FI_LOAN_OPERATION_CLEAR_ID,
    FI_LOAN_ID,
    FI_ADMIN_CENTER_ID,
    FI_OPERATION_CLEAR_ID,
    FI_OPERATION_REF_ID,
    FC_USER,
    FC_IP_ADDRESS,
    FD_CREATED_DATE,
    FD_MODIFICATION_DATE,
    FC_UUID_TRACKING )
VALUES(SE_LOAN_OPERATION_CLEAR_ID.NEXTVAL,
       PA_LOAN_ID,
       PA_ADMIN_CENTER_ID,
       PA_OPERATION_CLEAR_ID,
       PA_OPERATION_REF_ID,
       PA_USER,
       PA_IP_ADDRESS,
       SYSDATE,
       SYSDATE,
       PA_UUID_TRACKING )
;
COMMIT;
PA_STATUS_CODE := CSL_0;
  PA_STATUS_MSG  := CSL_SUCCESS;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    PA_STATUS_CODE := CSL_204;
    PA_STATUS_MSG  := CSL_NO_INSERTION;
    PA_STATUS_CODE := SQLCODE;
    PA_STATUS_MSG  := SQLERRM || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
    SC_CREDIT.SP_ERROR_LOG(
       UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_SP)
       ,SQLCODE
       ,SQLERRM
       ,DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
       ,NULL
       ,CSL_JSON
       );
END SP_INS_LOAN_OPERATION_CLEAR;

/

GRANT EXECUTE ON SC_CREDIT.SP_INS_LOAN_OPERATION_CLEAR TO USRNCPCREDIT1
/
