CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_SEL_PAYMENT_SCHEDULE (
  PA_LOAN_ID                   SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_LOAN_ID%TYPE
  ,PA_PMT_SCHEDULE_STATUS_ID   SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_PMT_SCHEDULE_STATUS_ID%TYPE DEFAULT NULL
  ,PA_CUR_RESULT               OUT SYS_REFCURSOR
  ,PA_STATUS_CODE              OUT NUMBER
  ,PA_STATUS_MSG               OUT VARCHAR2)

  AS
  -- GLOBAL CONSTANTS
  CSG_0                         CONSTANT SIMPLE_INTEGER := 0;
  CSG_1                         CONSTANT SIMPLE_INTEGER := 1;
  CSG_ARROW                     CONSTANT VARCHAR2(5) := ' -> ';
  CSG_X                         CONSTANT VARCHAR2(5) := 'X';
  CSG_SUCCESS_CODE              CONSTANT SIMPLE_INTEGER := 0;
  CSG_SUCCESS_MSG               CONSTANT VARCHAR2(10) := 'SUCCESS';
  CSG_NO_DATA_FOUND_CODE        CONSTANT SIMPLE_INTEGER := -20204;
  CSG_NO_DATA_FOUND_MSG         CONSTANT VARCHAR2(50) := 'THE DATA DOES NOT EXIST';
  CSG_SP_SEL_PAYMENT_SCHEDULE   CONSTANT VARCHAR2(50) := 'SP_SEL_PAYMENT_SCHEDULE';
  CSG_FORMAT_DATE               CONSTANT VARCHAR2(50) := 'YYYY-MM-DDTHH24:MI:SSTZH:TZM';
/*************************************************************
  PROJECT    :  NCP-OUTSTANDING BALANCE
  DESCRIPTION:  STORED PROCEDURE TO SELECT A PAYMENT SCHEDULE
  CREATOR:      JOS��� DE JES���S BRAVO AGUILAR/RICARDO HAZAEL GOMEZ ALVAREZ.
  CREATED DATE: AGO-02-2024
  MODIFICATION DATE: JAN-03-2025
*************************************************************/
  -- VARIABLES LOCALES
  VL_LOAN_ID                SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_LOAN_ID%TYPE;

  EXC_NO_DATA_FOUND         EXCEPTION;
  PRAGMA EXCEPTION_INIT (EXC_NO_DATA_FOUND, CSG_NO_DATA_FOUND_CODE);

  BEGIN
    PA_STATUS_CODE := CSG_SUCCESS_CODE;
    PA_STATUS_MSG  := CSG_SUCCESS_MSG;

  SELECT COUNT(*)
  INTO VL_LOAN_ID
  FROM SC_CREDIT.TA_PAYMENT_SCHEDULE
  WHERE FI_LOAN_ID = PA_LOAN_ID;
  IF VL_LOAN_ID = CSG_0 THEN
    RAISE EXC_NO_DATA_FOUND;
  END IF;

  OPEN PA_CUR_RESULT FOR
    SELECT
      FI_LOAN_ID
      ,FI_PAYMENT_NUMBER_ID
      ,FN_PAYMENT_AMOUNT
      ,TO_CHAR(CAST(FD_DUE_DATE AS TIMESTAMP WITH TIME ZONE), CSG_FORMAT_DATE) AS FD_DUE_DATE
      ,FI_PMT_SCHEDULE_STATUS_ID
    FROM SC_CREDIT.TA_PAYMENT_SCHEDULE
    WHERE FI_LOAN_ID = PA_LOAN_ID
    AND (PA_PMT_SCHEDULE_STATUS_ID IS NULL OR
        FI_PMT_SCHEDULE_STATUS_ID = PA_PMT_SCHEDULE_STATUS_ID);

  EXCEPTION
    WHEN EXC_NO_DATA_FOUND THEN
    PA_STATUS_CODE := CSG_NO_DATA_FOUND_CODE;
    PA_STATUS_MSG := CSG_NO_DATA_FOUND_MSG || CSG_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
    OPEN PA_CUR_RESULT FOR
      SELECT
      NULL FI_LOAN_ID
      ,NULL FI_PAYMENT_NUMBER_ID
      ,NULL FN_PAYMENT_AMOUNT
      ,NULL FD_DUE_DATE
      ,NULL FI_PMT_SCHEDULE_STATUS_ID
      FROM DUAL WHERE CSG_1 = CSG_0;

    WHEN OTHERS THEN
      PA_STATUS_CODE := SQLCODE;
      PA_STATUS_MSG := SQLERRM || CSG_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
      IF PA_CUR_RESULT%ISOPEN THEN
        CLOSE PA_CUR_RESULT;
      END IF;
      SC_CREDIT.SP_ERROR_LOG(CSG_SP_SEL_PAYMENT_SCHEDULE, SQLCODE, SQLERRM,
        DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, CSG_X, CSG_X);

  END SP_SEL_PAYMENT_SCHEDULE;

/

GRANT EXECUTE ON SC_CREDIT.SP_SEL_PAYMENT_SCHEDULE TO USRNCPCREDIT1
/
GRANT EXECUTE ON SC_CREDIT.SP_SEL_PAYMENT_SCHEDULE TO USRPURPOSEWS
/
