CREATE OR REPLACE  FUNCTION SC_CREDIT.FN_GET_NEXT_LOAN_BALANCE_ID RETURN SC_CREDIT.TA_LOAN_BALANCE.FI_LOAN_BALANCE_ID%TYPE IS
/*************************************************************
  PROJECT    :  NCP
  DESCRIPTION:  FUNCTION TO GET THE NEXT LOAN_BALANCE_ID VALUE.
  CREATOR:      JESUS BRAVO.
  CREATED DATE: AGO-13-2024
*************************************************************/
    VL_NEXT_LOAN_BALANCE_ID     SC_CREDIT.TA_LOAN_BALANCE.FI_LOAN_BALANCE_ID%TYPE;

  BEGIN
    VL_NEXT_LOAN_BALANCE_ID  := SC_CREDIT.SE_LOAN_BALANCE_ID.NEXTVAL;

    RETURN VL_NEXT_LOAN_BALANCE_ID;

  EXCEPTION
    WHEN OTHERS THEN
        VL_NEXT_LOAN_BALANCE_ID := -1;
        SC_CREDIT.SP_ERROR_LOG('FN_GET_NEXT_LOAN_BALANCE_ID', SQLCODE, SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, '', '');
        RETURN VL_NEXT_LOAN_BALANCE_ID;


END FN_GET_NEXT_LOAN_BALANCE_ID;

/

GRANT EXECUTE ON SC_CREDIT.FN_GET_NEXT_LOAN_BALANCE_ID TO USRNCPCREDIT1
/
