CREATE OR REPLACE  TYPE SC_CREDIT.TYP_REC_BTC_STATUS_DETAIL AS OBJECT (FI_LOAN_ID                 NUMBER(15,0) ,FI_ADMIN_CENTER_ID         NUMBER(8,0) ,FI_LOAN_STATUS_ID            NUMBER(5,0) ,FI_ACTION_DETAIL_ID        NUMBER(3,0) ,FI_COUNTER_DAY                 NUMBER(5,0) ,FD_INITIAL_DATE                VARCHAR(50) ,FI_PAYMENT_NUMBER_ID             NUMBER(8,0) ,FD_FINAL_DATE                    VARCHAR(50) ,FI_ON_OFF                    NUMBER(3,0) ,FI_OPTION                  NUMBER(3,0)
); 
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_STATUS_DETAIL TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_STATUS_DETAIL TO USRBTCCREDIT1;
