CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_UPD_WOFF (
    PTAB_PWO_AMOUNT_DETAIL          IN SC_CREDIT.TYP_TAB_BTC_STATUS_PWO
   ,PTAB_STATUS_DETAIL              IN SC_CREDIT.TYP_TAB_BTC_STATUS_DETAIL
   ,PA_UUID_TRACKING                IN  VARCHAR2
   ,PA_COMMIT                       IN NUMBER
   ,PA_STATUS_CODE                  OUT NUMBER
   ,PA_STATUS_MSG                   OUT VARCHAR2
   )
   IS
   /* **************************************************************
   * DESCRIPTION: UPDATE IN TABLE
   * PRECONDITIONS:
   * CREATED DATE: 21/11/2024
   * CREATOR: IVAN LOPEZ
   * MODIFICATION USER: AIXA SARMIENTO
   * MODIFICACTION DATE: 02/01/2025
   ************************************************************** */

   CSL_0                 CONSTANT SIMPLE_INTEGER := 0;
   CSL_1                 CONSTANT SIMPLE_INTEGER := 1;
   CSL_SP                CONSTANT SIMPLE_INTEGER := 1; --
   CSL_DATE_FORMAT       CONSTANT VARCHAR2(40)   := 'MM/DD/YYYY hh24:mi:ss';
   CSL_MSG_SUCCESS       CONSTANT VARCHAR2(20)   := 'SUCCESS';
   CSL_ARROW             CONSTANT VARCHAR2(5)    := '-->';                                      -- AESTHETICS SIGN
   CSL_SPACE             CONSTANT VARCHAR2(5)    := ' ';
   VL_I                  NUMBER(10) := 0;
   VL_II                 NUMBER(10) := 0;
   VL_STATUS_DETAIL      SC_CREDIT.TYP_TAB_BTC_STATUS_DETAIL;
   VL_DATA_IN            VARCHAR2(50);

   BEGIN

   PA_STATUS_CODE:= CSL_0;
   PA_STATUS_MSG := CSL_MSG_SUCCESS;

   VL_I := PTAB_STATUS_DETAIL.FIRST;
   VL_II := PTAB_PWO_AMOUNT_DETAIL.FIRST;

   UPDATE SC_CREDIT.TA_PWO_AMOUNT_DETAIL
      SET FD_MODIFICATION_DATE = SYSDATE,
          FN_AMOUNT_PAID = PTAB_PWO_AMOUNT_DETAIL(VL_II).FN_AMOUNT_PAID,
          FI_ADD_EXTENSION =PTAB_PWO_AMOUNT_DETAIL(VL_II).FI_ADD_EXTENSION,
          FN_PWO_MIN_PAYMENT = PTAB_PWO_AMOUNT_DETAIL(VL_II).FN_PWO_MIN_PAYMENT,
          FD_PWO_DATE = TO_DATE(PTAB_PWO_AMOUNT_DETAIL(VL_II).FD_PWO_DATE,CSL_DATE_FORMAT)
    WHERE FI_LOAN_ID = PTAB_PWO_AMOUNT_DETAIL(VL_II).FI_LOAN_ID
      AND FI_ADMIN_CENTER_ID = PTAB_PWO_AMOUNT_DETAIL(VL_II).FI_ADMIN_CENTER_ID;

   IF PA_COMMIT = CSL_1 THEN
         COMMIT;
   END IF;

   WHILE (VL_I IS NOT NULL) LOOP
      BEGIN
          INSERT INTO SC_CREDIT.TA_LOAN_STATUS_DETAIL
                 (FI_LOAN_ID
                 ,FI_ADMIN_CENTER_ID
                 ,FI_REGISTRATION_NUMBER
                 ,FI_LOAN_STATUS_ID
                 ,FI_ACTION_DETAIL_ID
                 ,FI_COUNTER_DAY
                 ,FD_INITIAL_DATE
                 ,FI_PAYMENT_NUMBER_ID
                 ,FD_FINAL_DATE
                 ,FI_ON_OFF
                 ,FC_USER
                 ,FD_CREATED_DATE
                 ,FD_MODIFICATION_DATE)
          VALUES (PTAB_STATUS_DETAIL(VL_I).FI_LOAN_ID
                 ,PTAB_STATUS_DETAIL(VL_I).FI_ADMIN_CENTER_ID
                 ,SC_CREDIT.SE_LOAN_STATUS_DETAIL.NEXTVAL
                 ,PTAB_STATUS_DETAIL(VL_I).FI_LOAN_STATUS_ID
                 ,PTAB_STATUS_DETAIL(VL_I).FI_ACTION_DETAIL_ID
                 ,PTAB_STATUS_DETAIL(VL_I).FI_COUNTER_DAY
                 ,TO_DATE(PTAB_STATUS_DETAIL(VL_I).FD_INITIAL_DATE,CSL_DATE_FORMAT)
                 ,PTAB_STATUS_DETAIL(VL_I).FI_PAYMENT_NUMBER_ID
                 ,TO_DATE(PTAB_STATUS_DETAIL(VL_I).FD_FINAL_DATE,CSL_DATE_FORMAT)
                 ,PTAB_STATUS_DETAIL(VL_I).FI_ON_OFF
                 ,USER
                 ,SYSDATE
                 ,SYSDATE
                 );
      EXCEPTION
        WHEN OTHERS THEN
           PA_STATUS_CODE := SQLCODE;
           PA_STATUS_MSG  := SQLERRM || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;

           VL_DATA_IN := PTAB_STATUS_DETAIL(VL_I).FI_LOAN_STATUS_ID
                         ||CSL_SPACE || PTAB_STATUS_DETAIL(VL_I).FI_ACTION_DETAIL_ID
                         ||CSL_SPACE || TO_DATE(PTAB_STATUS_DETAIL(VL_I).FD_INITIAL_DATE,CSL_DATE_FORMAT)
                         ||CSL_SPACE || TO_DATE(PTAB_STATUS_DETAIL(VL_I).FD_FINAL_DATE,CSL_DATE_FORMAT);

           SC_CREDIT.SP_ERROR_LOG('SP_UPD_WOFF', SQLCODE, SQLERRM,
             DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, PTAB_STATUS_DETAIL(VL_I).FI_LOAN_ID ||CSL_SPACE || PTAB_STATUS_DETAIL(VL_I).FI_ADMIN_CENTER_ID , VL_DATA_IN);
      END;
      VL_I := PTAB_STATUS_DETAIL.NEXT(VL_I);
      IF PA_COMMIT = CSL_1 THEN
         COMMIT;
      END IF;
   END LOOP;

EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK;
         PA_STATUS_CODE := SQLCODE;
         PA_STATUS_MSG := SQLERRM  || ' -> ' ||  DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
         SC_CREDIT.SP_ERROR_LOG(UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_SP)
                                    ,SQLCODE
                                    ,SQLERRM
                                    ,DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
                                    ,PA_UUID_TRACKING
                                    ,NULL);
END SP_UPD_WOFF;

/

GRANT EXECUTE ON SC_CREDIT.SP_UPD_WOFF TO USRNCPCREDIT1
/
