-- From TA_ERROR_LOG_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_ERROR_LOG (
   FI_LOG_ID NUMBER(15) NOT NULL,
   FD_ERROR date NOT NULL,
   FC_PROCESS VARCHAR2(80) NOT NULL,
   FI_SQL_CODE NUMBER(5),
   FC_SQL_ERRM VARCHAR2(1000),
   FC_BACKTRACE VARCHAR2(600),
   FC_UUID_TRACKING VARCHAR2(36) DEFAULT ' ' NOT NULL,
   FC_ADITIONAL VARCHAR2(500),
   FI_MONTH NUMBER(2),
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_ERROR_LOG_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FI_LOG_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FD_ERROR IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FC_PROCESS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FI_SQL_CODE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FC_SQL_ERRM IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FC_BACKTRACE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FC_UUID_TRACKING IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FC_ADITIONAL IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FI_MONTH IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_ERROR_LOG.FD_MODIFICATION_DATE IS '';

-- From TA_ERROR_LOG_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_ERROR_LOG ON SC_CREDIT.TA_ERROR_LOG(FI_LOG_ID) TABLESPACE USERS;

-- From TA_ERROR_LOG_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_ERROR_LOG
ADD
   CONSTRAINT PK_ERROR_LOG PRIMARY KEY (FI_LOG_ID) USING INDEX SC_CREDIT.IXPK_ERROR_LOG;

