-- From TA_LOAN_TOKEN_VOID_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_TOKEN_VOID (
   FI_LOAN_TOKEN_VOID_ID NUMBER(15) NOT NULL,
   FI_LOAN_OPERATION_VOID_ID NUMBER(15) NOT NULL,
   FI_LOAN_VOID_TOKEN NUMBER(15) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL
) TABLESPACE USERS;

COMMENT ON TABLE SC_CREDIT.TA_LOAN_TOKEN_VOID IS 'Table to store Tokens of each pending Void requests';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_TOKEN_VOID.FI_LOAN_TOKEN_VOID_ID IS 'ID of the row corresponding TO the TOKEN to be used when voiding after requesting day';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_TOKEN_VOID.FI_LOAN_OPERATION_VOID_ID IS 'ID of the Operation requesting Voiding of other Operation';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_TOKEN_VOID.FI_LOAN_VOID_TOKEN IS 'TOKEN to be used when voiding after requesting day';

-- From TA_LOAN_TOKEN_VOID_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_TOKEN_VOID ON SC_CREDIT.TA_LOAN_TOKEN_VOID(
   FI_LOAN_TOKEN_VOID_ID
) TABLESPACE USERS;

-- From TA_LOAN_TOKEN_VOID_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_TOKEN_VOID
ADD
   CONSTRAINT PK_LOAN_TOKEN_VOID PRIMARY KEY (
      FI_LOAN_TOKEN_VOID_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_TOKEN_VOID;

-- From TA_LOAN_TOKEN_VOID_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_TOKEN_VOID
ADD
   CONSTRAINT FK_LOAN_TOKEN_VOID_01 FOREIGN KEY (
      FI_LOAN_OPERATION_VOID_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION_VOID (
      FI_LOAN_OPERATION_VOID_ID
   );

