-- From TA_LOAN_OPERATION_TENDER_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_OPERATION_TENDER (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_OPERATION_ID NUMBER(15) NOT NULL,
   FI_TENDER_TYPE_ID NUMBER(4) NOT NULL,
   FI_OPERATION_TENDER_SEQ NUMBER(3) DEFAULT 1 NOT NULL,
   FN_OPERATION_AMOUNT NUMBER(12, 2) NOT NULL,
   FI_STATUS NUMBER(2) DEFAULT 1 NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_TENDER_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_TENDER.FI_LOAN_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_TENDER.FI_ADMIN_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_TENDER.FI_LOAN_OPERATION_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_TENDER.FI_TENDER_TYPE_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_TENDER.FI_OPERATION_TENDER_SEQ IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_TENDER.FN_OPERATION_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_TENDER.FI_STATUS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_TENDER.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_TENDER.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_TENDER.FD_MODIFICATION_DATE IS '';

-- From TA_LOAN_OPERATION_TENDER_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_OPERATION_TENDER ON SC_CREDIT.TA_LOAN_OPERATION_TENDER(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_LOAN_OPERATION_ID,
   FI_TENDER_TYPE_ID,
   FI_OPERATION_TENDER_SEQ
);

-- From TA_LOAN_OPERATION_TENDER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_TENDER
ADD
   CONSTRAINT PK_LOAN_OPERATION_TENDER PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_LOAN_OPERATION_ID,
      FI_TENDER_TYPE_ID,
      FI_OPERATION_TENDER_SEQ
   ) USING INDEX SC_CREDIT.IXPK_LOAN_OPERATION_TENDER;

-- From TA_LOAN_OPERATION_TENDER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_TENDER
ADD
   CONSTRAINT FK_LOAN_OPERATION_TENDER_01 FOREIGN KEY (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_OPERATION_TENDER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_TENDER
ADD
   CONSTRAINT FK_LOAN_OPERATION_TENDER_02 FOREIGN KEY (
      FI_TENDER_TYPE_ID
   ) REFERENCES SC_CREDIT.TC_TENDER_TYPE (
      FI_TENDER_TYPE_ID
   );

