-- From TA_LOAN_INTEREST_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_INTEREST (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_PAYMENT_NUMBER_ID NUMBER(3) NOT NULL,
   FI_DAYS_ACUM_BY_TERM NUMBER(4) NOT NULL,
   FI_PAYMENT_SCHEDULE_ID NUMBER(8) NOT NULL,
   FN_DAILY_INTEREST NUMBER(15, 5) NOT NULL,
   FN_ACCRUED_INTEREST_BALANCE NUMBER(15, 5) NOT NULL,
   FN_ACCRUED_INTEREST_LOAN NUMBER(15, 5) NOT NULL,
   FN_PAYMENT_INTEREST NUMBER(15, 5) NOT NULL,
   FC_CONDITION_INTEREST VARCHAR2(50) NOT NULL,
   FD_OPERATION_DATE date DEFAULT SYSDATE NOT NULL,
   FD_APPLICATION_DATE date DEFAULT SYSDATE NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL,
   FI_FLAG_AFFECT NUMBER(3) NOT NULL,
   FI_STATUS_INTEREST NUMBER(3) NOT NULL,
   FN_REMAIN NUMBER(15, 5) NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_INTEREST_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FI_LOAN_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FI_ADMIN_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FI_PAYMENT_NUMBER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FI_DAYS_ACUM_BY_TERM IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FI_PAYMENT_SCHEDULE_ID IS 'Loan payment schedule number';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FN_DAILY_INTEREST IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FN_ACCRUED_INTEREST_BALANCE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FN_ACCRUED_INTEREST_LOAN IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FN_PAYMENT_INTEREST IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FC_CONDITION_INTEREST IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FD_OPERATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FD_APPLICATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FD_MODIFICATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FI_FLAG_AFFECT IS 'Affectation for payment or void';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FI_STATUS_INTEREST IS 'Status interest for period number';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST.FN_REMAIN IS 'Remain for payment';

-- From TA_LOAN_INTEREST_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_INTEREST ON SC_CREDIT.TA_LOAN_INTEREST(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_PAYMENT_NUMBER_ID,
   FI_DAYS_ACUM_BY_TERM,
   FI_PAYMENT_SCHEDULE_ID
);

-- From TA_LOAN_INTEREST_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_INTEREST
ADD
   CONSTRAINT PK_LOAN_INTEREST PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_PAYMENT_NUMBER_ID,
      FI_DAYS_ACUM_BY_TERM,
      FI_PAYMENT_SCHEDULE_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_INTEREST;

-- From TA_LOAN_INTEREST_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_INTEREST
ADD
   CONSTRAINT FK_LOAN_INTEREST_01 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

