-- From TA_LOAN_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_COUNTRY_ID NUMBER(3) NOT NULL,
   FI_COMPANY_ID NUMBER(3) NOT NULL,
   FI_BUSINESS_UNIT_ID NUMBER(5) NOT NULL,
   FI_ORIGINATION_CENTER_ID NUMBER(8) NOT NULL,
   FC_PLATFORM_ID VARCHAR2(6) DEFAULT '0' NOT NULL,
   FC_SUB_PLATFORM_ID VARCHAR2(6) DEFAULT '0' NOT NULL,
   FC_CUSTOMER_ID VARCHAR2(36) NOT NULL,
   FI_PRODUCT_ID NUMBER(10) NOT NULL,
   FN_PRINCIPAL_AMOUNT NUMBER(12, 2) NOT NULL,
   FN_FINANCE_CHARGE_AMOUNT NUMBER(12, 2) NOT NULL,
   FN_PAID_INTEREST_AMOUNT NUMBER(12, 2) DEFAULT 0.0 NOT NULL,
   FN_PRINCIPAL_BALANCE NUMBER(12, 2) NOT NULL,
   FN_FINANCE_CHARGE_BALANCE NUMBER(12, 2) NOT NULL,
   FN_ADDITIONAL_CHARGE_BALANCE NUMBER(12, 2) NOT NULL,
   FD_ORIGINATION_DATE date NOT NULL,
   FD_FIRST_PAYMENT date NOT NULL,
   FD_DUE_DATE date NOT NULL,
   FN_APR NUMBER(12, 6) NOT NULL,
   FI_ADDITIONAL_STATUS NUMBER(5) NOT NULL,
   FI_CURRENT_BALANCE_SEQ NUMBER(5) NOT NULL,
   FN_INTEREST_RATE NUMBER(12, 2) NOT NULL,
   FI_NUMBER_OF_PAYMENTS NUMBER(5) NOT NULL,
   FI_TERM_TYPE NUMBER(5) NOT NULL,
   FI_LOAN_STATUS_ID NUMBER(5) NOT NULL,
   FD_LOAN_STATUS_DATE date DEFAULT SYSDATE NOT NULL,
   FC_SUBPRODUCT_ID VARCHAR2(10),
   FI_ACCRUED_TYPE_ID NUMBER(5) NOT NULL,
   FI_RULE_ID NUMBER(10) NOT NULL,
   FC_END_USER VARCHAR2(10) DEFAULT '0' NOT NULL,
   FD_OPERATION_DATE date NOT NULL,
   FI_TRANSACTION NUMBER(33),
   FD_LOAN_EFFECTIVE_DATE date,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FC_DEVICE VARCHAR2(50) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL,
   FI_SUBTERM_TYPE_ID NUMBER(5) DEFAULT 0 NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_LOAN_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_ADMIN_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_COUNTRY_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_COMPANY_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_BUSINESS_UNIT_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_ORIGINATION_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FC_PLATFORM_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FC_SUB_PLATFORM_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FC_CUSTOMER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_PRODUCT_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FN_PRINCIPAL_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FN_FINANCE_CHARGE_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FN_PAID_INTEREST_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FN_PRINCIPAL_BALANCE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FN_FINANCE_CHARGE_BALANCE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FN_ADDITIONAL_CHARGE_BALANCE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FD_ORIGINATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FD_FIRST_PAYMENT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FD_DUE_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FN_APR IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_ADDITIONAL_STATUS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_CURRENT_BALANCE_SEQ IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FN_INTEREST_RATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_NUMBER_OF_PAYMENTS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_TERM_TYPE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_LOAN_STATUS_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FD_LOAN_STATUS_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FC_SUBPRODUCT_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_ACCRUED_TYPE_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_RULE_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FC_END_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FD_OPERATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_TRANSACTION IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FD_LOAN_EFFECTIVE_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FC_UUID_TRACKING IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FC_IP_ADDRESS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FC_DEVICE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FD_MODIFICATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN.FI_SUBTERM_TYPE_ID IS 'SUBTERM TYPE THE LOAN';

-- From TA_LOAN_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN ON SC_CREDIT.TA_LOAN(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID
);

-- From TA_LOAN_CRT_INDEX_HU-00001.xml
CREATE INDEX SC_CREDIT.IX_LOAN02 ON SC_CREDIT.TA_LOAN(
   FI_ADMIN_CENTER_ID,
   FI_LOAN_STATUS_ID
);

-- From TA_LOAN_CRT_INDEX_HU-00001.xml
CREATE INDEX SC_CREDIT.IX03_LOAN ON SC_CREDIT.TA_LOAN(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FC_CUSTOMER_ID
);

-- From TA_LOAN_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN
ADD
   CONSTRAINT PK_LOAN PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN;

-- From TA_LOAN_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN
ADD
   CONSTRAINT FK_LOAN_04 FOREIGN KEY (
      FI_ADMIN_CENTER_ID,
      FI_BUSINESS_UNIT_ID,
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   ) REFERENCES SC_CREDIT.TC_CENTER (
      FI_CENTER_ID,
      FI_BUSINESS_UNIT_ID,
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   );

-- From TA_LOAN_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN
ADD
   CONSTRAINT FK_LOAN_01 FOREIGN KEY (
      FI_BUSINESS_UNIT_ID,
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   ) REFERENCES SC_CREDIT.TC_BUSINESS_UNIT (
      FI_BUSINESS_UNIT_ID,
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   );

-- From TA_LOAN_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN
ADD
   CONSTRAINT FK_LOAN_06 FOREIGN KEY (FI_PRODUCT_ID) REFERENCES SC_CREDIT.TC_PRODUCT (FI_PRODUCT_ID);

-- From TA_LOAN_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN
ADD
   CONSTRAINT FK_LOAN_07 FOREIGN KEY (FI_TERM_TYPE) REFERENCES SC_CREDIT.TC_TERM_TYPE (
      FI_TERM_TYPE_ID
   );

-- From TA_LOAN_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN
ADD
   CONSTRAINT FK_LOAN_05 FOREIGN KEY (
      FI_LOAN_STATUS_ID
   ) REFERENCES SC_CREDIT.TC_LOAN_STATUS (
      FI_LOAN_STATUS_ID
   );

-- From TA_LOAN_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN
ADD
   CONSTRAINT FK_LOAN_03 FOREIGN KEY (
      FI_ACCRUED_TYPE_ID
   ) REFERENCES SC_CREDIT.TC_ACCRUED_TYPE (
      FI_ACCRUED_TYPE_ID
   );

-- From TA_LOAN_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN
ADD
   CONSTRAINT FK_LOAN_08 FOREIGN KEY (
      FI_SUBTERM_TYPE_ID
   ) REFERENCES SC_CREDIT.TC_SUBTERM_TYPE (
      FI_SUBTERM_TYPE_ID
   );

