-- From TA_LOAN_INSURANCE_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_INSURANCE (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_INSURANCE_ID NUMBER(15) NOT NULL,
   FI_INSURANCE_ACTIVE NUMBER(2) NOT NULL,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FC_DEVICE VARCHAR2(50) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_INSURANCE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_INSURANCE ON SC_CREDIT.TA_LOAN_INSURANCE(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID
) TABLESPACE USERS;

-- From TA_LOAN_INSURANCE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IX_LOAN_INSURANCE_01 ON SC_CREDIT.TA_LOAN_INSURANCE(
   FI_LOAN_INSURANCE_ID
) TABLESPACE USERS;

-- From TA_LOAN_INSURANCE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_INSURANCE
ADD
   CONSTRAINT PK_LOAN_INSURANCE PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_INSURANCE;

-- From TA_LOAN_INSURANCE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_INSURANCE
ADD
   CONSTRAINT FK_LOAN_INSURANCE_01 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_INSURANCE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_INSURANCE
ADD
   CONSTRAINT UQ_LOAN_INSURANCE UNIQUE (
      FI_LOAN_INSURANCE_ID
   ) USING INDEX SC_CREDIT.IX_LOAN_INSURANCE_01;

