-- From TA_LOAN_MISCELLAN_OPERATIONS_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_MISCELLAN_OPERATIONS (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_OPERATION_ID NUMBER(15) NOT NULL,
   FI_MISCELLAN_OPERATIONS_ID NUMBER(3) NOT NULL,
   FD_APPLICATION_DATE date NOT NULL,
   FI_TRANSACTION NUMBER(33) NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) NOT NULL,
   FC_DEVICE VARCHAR2(50) NOT NULL,
   FI_STATUS NUMBER(2) DEFAULT 1 NOT NULL,
   FC_USER VARCHAR2(30) NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_MISCELLAN_OPERATIONS_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_MISCELLAN_OPERATIONS ON SC_CREDIT.TA_LOAN_MISCELLAN_OPERATIONS(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_LOAN_OPERATION_ID
) TABLESPACE USERS;

-- From TA_LOAN_MISCELLAN_OPERATIONS_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_MISCELLAN_OPERATIONS
ADD
   CONSTRAINT PK_LOAN_MISCELLAN_OPERATIONS PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_LOAN_OPERATION_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_MISCELLAN_OPERATIONS;

-- From TA_LOAN_MISCELLAN_OPERATIONS_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_MISCELLAN_OPERATIONS
ADD
   CONSTRAINT FK_LOAN_MISCELLAN_OPERATIONS_01 FOREIGN KEY (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_MISCELLAN_OPERATIONS_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_MISCELLAN_OPERATIONS
ADD
   CONSTRAINT FK_LOAN_MISCELLAN_OPERATIONS_02 FOREIGN KEY (
      FI_MISCELLAN_OPERATIONS_ID
   ) REFERENCES SC_CREDIT.TC_LOAN_MISCELLAN_OPERATIONS (
      FI_MISCELLAN_OPERATIONS_ID
   );

