-- From TA_LOAN_STATUS_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_STATUS (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_OPERATION_ID NUMBER(15) NOT NULL,
   FI_LOAN_STATUS_ID NUMBER(5) NOT NULL,
   FI_LOAN_STATUS_OLD_ID NUMBER(5) NOT NULL,
   FI_TRIGGER_ID NUMBER(3) NOT NULL,
   FD_LOAN_STATUS_DATE date,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_STATUS_CRTB_HU-00001.xml
COMMENT ON TABLE SC_CREDIT.TA_LOAN_STATUS IS 'Table containing status changes';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS.FI_LOAN_ID IS 'Loan Identifier';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS.FI_ADMIN_CENTER_ID IS 'Loan Management Center';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS.FI_LOAN_OPERATION_ID IS 'Loan Identifier Operation';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS.FI_LOAN_STATUS_ID IS 'The new status';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS.FI_LOAN_STATUS_OLD_ID IS 'The old status';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS.FI_TRIGGER_ID IS 'The id trigger';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS.FD_LOAN_STATUS_DATE IS 'Status change date';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS.FD_MODIFICATION_DATE IS '';

-- From TA_LOAN_STATUS_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_STATUS ON SC_CREDIT.TA_LOAN_STATUS(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_LOAN_OPERATION_ID
);

-- From TA_LOAN_STATUS_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_STATUS
ADD
   CONSTRAINT PK_LOAN_STATUS PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_LOAN_OPERATION_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_STATUS;

-- From TA_LOAN_STATUS_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_STATUS
ADD
   CONSTRAINT FK_LOAN_STATUS_02 FOREIGN KEY (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_STATUS_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_STATUS
ADD
   CONSTRAINT FK_LOAN_STATUS_01 FOREIGN KEY (
      FI_LOAN_STATUS_ID,
      FI_LOAN_STATUS_OLD_ID,
      FI_TRIGGER_ID
   ) REFERENCES SC_CREDIT.TC_LOAN_STATUS_TRIGGER (
      FI_NEXT_STATUS,
      FI_LOAN_STATUS_ID,
      FI_TRIGGER_ID
   );

