-- From TA_LOAN_GLOBAL_DETAIL_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_GLOBAL_DETAIL (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FN_PAYMENT_AMOUNT NUMBER(12, 2) NOT NULL,
   FN_LAST_PAYMENT_AMOUNT NUMBER(12, 2) NOT NULL,
   FC_INTEREST_TYPE VARCHAR2(15) NOT NULL,
   FD_CACELLATION_DATE date NOT NULL,
   FN_TOTAL_PAID NUMBER(12, 2) NOT NULL,
   FN_TOTAL_ACCRUED NUMBER(12, 2) NOT NULL,
   FN_FULL_PAYMENT NUMBER(12, 2) NOT NULL,
   FN_FULL_PAYMENT_DISCOUNT NUMBER(12, 2) DEFAULT 0.0 NOT NULL,
   FN_ORIGINAL_INTEREST NUMBER(12, 2) NOT NULL,
   FN_PAID_INTEREST_AMOUNT NUMBER(12, 2) NOT NULL,
   FN_ACCRUED_INTEREST_BALANCE NUMBER(12, 2) NOT NULL,
   FI_PAYED_PERIOD INTEGER NOT NULL,
   FI_ELAPSED_PERIOD INTEGER NOT NULL,
   FI_MISSED_PERIOD INTEGER NOT NULL,
   FD_ACCRUAL_START_DATE date NOT NULL,
   FN_OUTSTANDING_BALANCE NUMBER(12, 2) DEFAULT 0.0 NOT NULL,
   FC_END_USER VARCHAR2(10) DEFAULT 0 NOT NULL,
   FI_LOAN_INSURANCE_ID NUMBER(15),
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FC_DEVICE VARCHAR2(50) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_GLOBAL_DETAIL_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FI_LOAN_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FI_ADMIN_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FN_PAYMENT_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FN_LAST_PAYMENT_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FC_INTEREST_TYPE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FD_CACELLATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FN_TOTAL_PAID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FN_TOTAL_ACCRUED IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FN_FULL_PAYMENT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FN_FULL_PAYMENT_DISCOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FN_ORIGINAL_INTEREST IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FN_PAID_INTEREST_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FN_ACCRUED_INTEREST_BALANCE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FI_PAYED_PERIOD IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FI_ELAPSED_PERIOD IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FI_MISSED_PERIOD IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FD_ACCRUAL_START_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FN_OUTSTANDING_BALANCE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FC_END_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FI_LOAN_INSURANCE_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FC_UUID_TRACKING IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FC_IP_ADDRESS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FC_DEVICE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_GLOBAL_DETAIL.FD_MODIFICATION_DATE IS '';

-- From TA_LOAN_GLOBAL_DETAIL_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_GLOBAL_DETAIL ON SC_CREDIT.TA_LOAN_GLOBAL_DETAIL(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID
);

-- From TA_LOAN_GLOBAL_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_GLOBAL_DETAIL
ADD
   CONSTRAINT PK_LOAN_GLOBAL_DETAIL PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_GLOBAL_DETAIL;

-- From TA_LOAN_GLOBAL_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_GLOBAL_DETAIL
ADD
   CONSTRAINT FK_LOAN_GLOBAL_DETAIL_01 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_GLOBAL_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_GLOBAL_DETAIL
ADD
   CONSTRAINT FK_LOAN_GLOBAL_DETAIL_02 FOREIGN KEY (
      FI_LOAN_INSURANCE_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_INSURANCE (
      FI_LOAN_INSURANCE_ID
   );

