-- From TA_LOAN_BALANCE_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_BALANCE (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_BALANCE_ID NUMBER(15) NOT NULL,
   FI_LOAN_OPERATION_ID NUMBER(15) NOT NULL,
   FI_BALANCE_SEQ NUMBER(5),
   FN_PRINCIPAL_BALANCE NUMBER(12, 2) NOT NULL,
   FN_FINANCE_CHARGE_BALANCE NUMBER(12, 2) NOT NULL,
   FN_ADDITIONAL_CHARGE_BALANCE NUMBER(12, 2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_BALANCE_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FI_LOAN_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FI_ADMIN_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FI_LOAN_BALANCE_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FI_LOAN_OPERATION_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FI_BALANCE_SEQ IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FN_PRINCIPAL_BALANCE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FN_FINANCE_CHARGE_BALANCE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FN_ADDITIONAL_CHARGE_BALANCE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_BALANCE.FD_MODIFICATION_DATE IS '';

-- From TA_LOAN_BALANCE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_BALANCE ON SC_CREDIT.TA_LOAN_BALANCE(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_LOAN_BALANCE_ID
);

-- From TA_LOAN_BALANCE_CRT_INDEX_HU-00001.xml
CREATE INDEX SC_CREDIT.IX_LOAN_BALANCE01 ON SC_CREDIT.TA_LOAN_BALANCE(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_BALANCE_SEQ
);

-- From TA_LOAN_BALANCE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_BALANCE
ADD
   CONSTRAINT PK_LOAN_BALANCE PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_LOAN_BALANCE_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_BALANCE;

-- From TA_LOAN_BALANCE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_BALANCE
ADD
   CONSTRAINT FK_LOAN_BALANCE_01 FOREIGN KEY (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_BALANCE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_BALANCE
ADD
   CONSTRAINT FK_LOAN_BALANCE_02 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

