-- From TA_LOAN_OPERATION_PARENT_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_OPERATION_PARENT (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_OPER_PARENT_ID NUMBER(15) NOT NULL,
   FI_LOAN_OPER_CHILD_ID NUMBER(15) NOT NULL,
   FI_STATUS NUMBER(2) DEFAULT 1 NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_PARENT_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_OPERATION_PARENT ON SC_CREDIT.TA_LOAN_OPERATION_PARENT(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_LOAN_OPER_PARENT_ID,
   FI_LOAN_OPER_CHILD_ID
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_PARENT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_PARENT
ADD
   CONSTRAINT PK_LOAN_OPERATION_PARENT PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_LOAN_OPER_PARENT_ID,
      FI_LOAN_OPER_CHILD_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_OPERATION_PARENT;

-- From TA_LOAN_OPERATION_PARENT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_PARENT
ADD
   CONSTRAINT FK_LOAN_OPERATION_PARENT_01 FOREIGN KEY (
      FI_LOAN_OPER_PARENT_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_OPERATION_PARENT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_PARENT
ADD
   CONSTRAINT FK_LOAN_OPERATION_PARENT_02 FOREIGN KEY (
      FI_LOAN_OPER_CHILD_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

