-- From TA_LOAN_OPERATION_VOID_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_OPERATION_VOID (
   FI_LOAN_OPERATION_VOID_ID NUMBER(15) NOT NULL,
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_OPERATION_REQUEST_ID NUMBER(15) NOT NULL,
   FI_OPERATION_TYPE_ID NUMBER(5) NOT NULL,
   FI_OPERATION_REVERSED_ID NUMBER(15) NOT NULL,
   FC_REVERSE_REASON VARCHAR2(30) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL
) TABLESPACE USERS;

COMMENT ON TABLE SC_CREDIT.TA_LOAN_OPERATION_VOID IS 'Table to handle requests for Voiding an Operation';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_LOAN_OPERATION_VOID_ID IS 'Request ID for voiding an operation';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_LOAN_ID IS 'Identifier of the Loan';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_ADMIN_CENTER_ID IS 'Management Center';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_OPERATION_REQUEST_ID IS 'ID of Operation requesting reverse of previous operation';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_OPERATION_TYPE_ID IS 'Identifier of type of operation performed';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_OPERATION_REVERSED_ID IS 'ID for Voided Operation';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_VOID.FC_REVERSE_REASON IS 'Reason for reversing the operation';

-- From TA_LOAN_OPERATION_VOID_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_OPERATION_VOID ON SC_CREDIT.TA_LOAN_OPERATION_VOID(
   FI_LOAN_OPERATION_VOID_ID
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_VOID_CRT_INDEX_HU-00001.xml
CREATE INDEX SC_CREDIT.IX01_LOAN_OPERATION_VOID ON SC_CREDIT.TA_LOAN_OPERATION_VOID(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_OPERATION_REVERSED_ID
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_VOID_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_VOID
ADD
   CONSTRAINT PK_LOAN_OPERATION_VOID PRIMARY KEY (
      FI_LOAN_OPERATION_VOID_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_OPERATION_VOID;

-- From TA_LOAN_OPERATION_VOID_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_VOID
ADD
   CONSTRAINT FK_LOAN_OPERATION_VOID_01 FOREIGN KEY (
      FI_OPERATION_REQUEST_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_OPERATION_VOID_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_VOID
ADD
   CONSTRAINT FK_LOAN_OPERATION_VOID_02 FOREIGN KEY (
      FI_OPERATION_TYPE_ID
   ) REFERENCES SC_CREDIT.TC_OPERATION_TYPE (
      FI_OPERATION_TYPE_ID
   );

