-- From TA_LOAN_INTEREST_DETAIL_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_INTEREST_DETAIL (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_INTEREST_ID NUMBER(15) NOT NULL,
   FI_PAYMENT_SCHEDULE_ID NUMBER(3) NOT NULL,
   FI_DAYS_ACUM_BY_TERM NUMBER(4) NOT NULL,
   FN_DAILY_INTEREST NUMBER(15, 5) NOT NULL,
   FN_ACCRUED_INTEREST_BALANCE NUMBER(15, 5) NOT NULL,
   FN_ACCRUED_INTEREST_LOAN NUMBER(15, 5) NOT NULL,
   FN_PAYMENT_INTEREST NUMBER(15, 5) NOT NULL,
   FN_REMAIN NUMBER(15, 5) NOT NULL,
   FC_CONDITION_INTEREST VARCHAR2(50) NOT NULL,
   FD_OPERATION_DATE date DEFAULT SYSDATE NOT NULL,
   FD_APPLICATION_DATE date DEFAULT SYSDATE NOT NULL,
   FI_LOAN_OPERATION_ID NUMBER(15) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_INTEREST_DETAIL_CRTB_HU-00001.xml
COMMENT ON TABLE SC_CREDIT.TA_LOAN_INTEREST_DETAIL IS 'Table interest daily  detail';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FI_LOAN_ID IS 'Loan Identifier';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FI_ADMIN_CENTER_ID IS 'Loan Management Center';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FI_LOAN_INTEREST_ID IS 'Id loan Identifier';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FI_PAYMENT_SCHEDULE_ID IS 'Loan payment schedule number';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FI_DAYS_ACUM_BY_TERM IS 'Accumulated days of the period';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FN_DAILY_INTEREST IS 'Interest daily';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FN_ACCRUED_INTEREST_BALANCE IS 'Accumulated interest as of the day of the period';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FN_ACCRUED_INTEREST_LOAN IS 'Accumulated daily interest on the loan';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FN_PAYMENT_INTEREST IS 'Payment of interest on the loan';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FN_REMAIN IS 'Remain for payment';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FC_CONDITION_INTEREST IS 'Description of the condition that applied to the interest of the loan';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FD_OPERATION_DATE IS 'Date operation calculate interest';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FD_APPLICATION_DATE IS 'Date application calculate interest';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FI_LOAN_OPERATION_ID IS 'Id operation for loan';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_INTEREST_DETAIL.FD_MODIFICATION_DATE IS '';

-- From TA_LOAN_INTEREST_DETAIL_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_INTEREST_DETAIL ON SC_CREDIT.TA_LOAN_INTEREST_DETAIL(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_LOAN_INTEREST_ID
);

-- From TA_LOAN_INTEREST_DETAIL_CRT_INDEX_HU-00001.xml
CREATE INDEX SC_CREDIT.IX01_LOAN_INTEREST_DETAIL ON SC_CREDIT.TA_LOAN_INTEREST_DETAIL(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_PAYMENT_SCHEDULE_ID,
   FI_DAYS_ACUM_BY_TERM
);

-- From TA_LOAN_INTEREST_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_INTEREST_DETAIL
ADD
   CONSTRAINT PK_LOAN_INTEREST_DETAIL PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_LOAN_INTEREST_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_INTEREST_DETAIL;

-- From TA_LOAN_INTEREST_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_INTEREST_DETAIL
ADD
   CONSTRAINT FK_LOAN_INTEREST_DETAIL_01 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

