-- From TA_LOAN_OPERATION_REF_PAYMENT_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT (
   FI_LOAN_OPERATION_REF_PAYMENT_ID NUMBER(15) NOT NULL,
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_OPERATION_REF_ID NUMBER(15) NOT NULL,
   FC_REFERENCE_ID VARCHAR2(36),
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL
) TABLESPACE USERS;

COMMENT ON TABLE SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT IS 'Table to record the transaction payment reference';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT.FI_LOAN_ID IS 'Identifier of the Loan';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT.FI_ADMIN_CENTER_ID IS 'Management Center';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT.FI_OPERATION_REF_ID IS 'ID of Operation requesting reverse of previous operation';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT.FC_REFERENCE_ID IS 'Identifier of reference payment';

-- From TA_LOAN_OPERATION_REF_PAYMENT_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_OPERATION_REF_PAYMENT ON SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT(
   FI_LOAN_OPERATION_REF_PAYMENT_ID
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_REF_PAYMENT_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.UQ_LOAN_OPERATION_REF_PAYMENT ON SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT(
   FI_OPERATION_REF_ID,
   FC_REFERENCE_ID
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_REF_PAYMENT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT
ADD
   CONSTRAINT PK_LOAN_OPERATION_REF_PAYMENT PRIMARY KEY (
      FI_LOAN_OPERATION_REF_PAYMENT_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_OPERATION_REF_PAYMENT;

-- From TA_LOAN_OPERATION_REF_PAYMENT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT
ADD
   CONSTRAINT FK_LOAN_OPERATION_REF_PAYMENT_01 FOREIGN KEY (
      FI_OPERATION_REF_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

