-- From TA_LOAN_OPERATION_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_OPERATION (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_OPERATION_ID NUMBER(15) NOT NULL,
   FI_COUNTRY_ID NUMBER(3) NOT NULL,
   FI_COMPANY_ID NUMBER(3) NOT NULL,
   FI_BUSINESS_UNIT_ID NUMBER(5) NOT NULL,
   FI_OPERATION_TYPE_ID NUMBER(5) NOT NULL,
   FI_TRANSACTION NUMBER(33),
   FC_PLATFORM_ID VARCHAR2(6) DEFAULT '0' NOT NULL,
   FC_SUB_PLATFORM_ID VARCHAR2(6) DEFAULT '0' NOT NULL,
   FN_OPERATION_AMOUNT NUMBER(12, 2) NOT NULL,
   FD_APPLICATION_DATE date NOT NULL,
   FD_OPERATION_DATE date NOT NULL,
   FI_STATUS NUMBER(3) DEFAULT 1 NOT NULL,
   FC_END_USER VARCHAR2(10) NOT NULL,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL,
   FC_GPS_LATITUDE VARCHAR2(15) NOT NULL,
   FC_GPS_LONGITUDE VARCHAR2(15) NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FC_DEVICE VARCHAR2(50) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FI_LOAN_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FI_ADMIN_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FI_LOAN_OPERATION_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FI_COUNTRY_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FI_COMPANY_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FI_BUSINESS_UNIT_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FI_OPERATION_TYPE_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FI_TRANSACTION IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FC_PLATFORM_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FC_SUB_PLATFORM_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FN_OPERATION_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FD_APPLICATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FD_OPERATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FI_STATUS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FC_END_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FC_UUID_TRACKING IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FC_GPS_LATITUDE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FC_GPS_LONGITUDE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FC_IP_ADDRESS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FC_DEVICE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION.FD_MODIFICATION_DATE IS '';

-- From TA_LOAN_OPERATION_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_OPERATION ON SC_CREDIT.TA_LOAN_OPERATION(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_LOAN_OPERATION_ID
);

-- From TA_LOAN_OPERATION_CRT_INDEX_HU-00001.xml
CREATE INDEX SC_CREDIT.IX01LOAN_OPERATION ON SC_CREDIT.TA_LOAN_OPERATION(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_OPERATION_TYPE_ID
);

-- From TA_LOAN_OPERATION_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION
ADD
   CONSTRAINT PK_LOAN_OPERATION PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_LOAN_OPERATION_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_OPERATION;

-- From TA_LOAN_OPERATION_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION
ADD
   CONSTRAINT FK_LOAN_OPERATION_01 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_OPERATION_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION
ADD
   CONSTRAINT FK_LOAN_OPERATION_03 FOREIGN KEY (
      FI_ADMIN_CENTER_ID,
      FI_BUSINESS_UNIT_ID,
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   ) REFERENCES SC_CREDIT.TC_CENTER (
      FI_CENTER_ID,
      FI_BUSINESS_UNIT_ID,
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   );

-- From TA_LOAN_OPERATION_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION
ADD
   CONSTRAINT FK_LOAN_OPERATION_02 FOREIGN KEY (
      FI_OPERATION_TYPE_ID
   ) REFERENCES SC_CREDIT.TC_OPERATION_TYPE (
      FI_OPERATION_TYPE_ID
   );

