-- From TA_LOAN_OPERATION_CLEAR_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_OPERATION_CLEAR (
   FI_LOAN_OPERATION_CLEAR_ID NUMBER(15) NOT NULL,
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_OPERATION_CLEAR_ID NUMBER(15) NOT NULL,
   FI_OPERATION_REF_ID NUMBER(15) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL
) TABLESPACE USERS;

COMMENT ON TABLE SC_CREDIT.TA_LOAN_OPERATION_CLEAR IS 'Table to record the approval of the payment reference';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FI_LOAN_ID IS 'Identifier of the Loan';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FI_ADMIN_CENTER_ID IS 'Management Center';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FI_OPERATION_CLEAR_ID IS 'ID of Operation requesting clear of previous operation';

COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_CLEAR.FI_OPERATION_REF_ID IS 'ID of Operation reference payment of previous operation';

-- From TA_LOAN_OPERATION_CLEAR_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_OPERATION_CLEAR ON SC_CREDIT.TA_LOAN_OPERATION_CLEAR(
   FI_LOAN_OPERATION_CLEAR_ID
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_CLEAR_CRT_INDEX_HU-00001.xml
CREATE INDEX SC_CREDIT.IX01_OPERATION_REF_ID ON SC_CREDIT.TA_LOAN_OPERATION_CLEAR(
   FI_OPERATION_REF_ID
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_CLEAR_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_CLEAR
ADD
   CONSTRAINT PK_LOAN_OPERATION_CLEAR PRIMARY KEY (
      FI_LOAN_OPERATION_CLEAR_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_OPERATION_CLEAR;

-- From TA_LOAN_OPERATION_CLEAR_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_CLEAR
ADD
   CONSTRAINT FK_LOAN_OPERATION_CLEAR_01 FOREIGN KEY (
      FI_OPERATION_CLEAR_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

