-- From TA_LOAN_SCORING_DETAIL_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_SCORING_DETAIL (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_SCORING_DETAIL_ID NUMBER(15) NOT NULL,
   FI_OPERATION_TYPE_ID NUMBER(5) NOT NULL,
   FI_TRANSACTION NUMBER(33) NOT NULL,
   FN_OPERATION_AMOUNT NUMBER(12, 2) NOT NULL,
   FD_OPERATION_DATE date NOT NULL,
   FI_STATUS NUMBER(3) DEFAULT 1 NOT NULL,
   FC_END_USER VARCHAR2(10) NOT NULL,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL,
   FC_DEVICE_ID VARCHAR2(50) NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_SCORING_DETAIL_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FI_LOAN_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FI_ADMIN_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FI_LOAN_SCORING_DETAIL_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FI_OPERATION_TYPE_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FI_TRANSACTION IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FN_OPERATION_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FD_OPERATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FI_STATUS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FC_END_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FC_UUID_TRACKING IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FC_DEVICE_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FC_IP_ADDRESS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING_DETAIL.FD_MODIFICATION_DATE IS '';

-- From TA_LOAN_SCORING_DETAIL_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_SCORING_DETAIL ON SC_CREDIT.TA_LOAN_SCORING_DETAIL(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID
);

-- From TA_LOAN_SCORING_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_SCORING_DETAIL
ADD
   CONSTRAINT PK_LOAN_SCORING_DETAIL_ID PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_SCORING_DETAIL;

-- From TA_LOAN_SCORING_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_SCORING_DETAIL
ADD
   CONSTRAINT FK_LOAN_SCORING_DETAIL_01 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_SCORING (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

