-- From TA_LOAN_STATUS_DETAIL_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_STATUS_DETAIL (
   FI_REGISTRATION_NUMBER NUMBER(12) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_LOAN_STATUS_ID NUMBER(5) NOT NULL,
   FI_ACTION_DETAIL_ID NUMBER(3) NOT NULL,
   FI_COUNTER_DAY NUMBER(5) NOT NULL,
   FD_INITIAL_DATE date NOT NULL,
   FI_PAYMENT_NUMBER_ID NUMBER(8) NOT NULL,
   FD_FINAL_DATE date,
   FI_ON_OFF NUMBER(3) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_STATUS_DETAIL_CRTB_HU-00001.xml
COMMENT ON TABLE SC_CREDIT.TA_LOAN_STATUS_DETAIL IS 'Table containing the details of the Loan status changes';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FI_REGISTRATION_NUMBER IS 'Loan Record Number';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FI_ADMIN_CENTER_ID IS 'Loan Management Center';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FI_LOAN_ID IS 'Loan Identifier';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FI_LOAN_STATUS_ID IS 'Current Loan Status';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FI_ACTION_DETAIL_ID IS 'Action Triggering the Loan Status';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FI_COUNTER_DAY IS 'Status Duration Counter';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FD_INITIAL_DATE IS 'Status Start Date';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FI_PAYMENT_NUMBER_ID IS 'Loan Payment Number';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FD_FINAL_DATE IS 'Loan Status End Date';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FI_ON_OFF IS 'Record On/Off Indicator';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FD_MODIFICATION_DATE IS '';

-- From TA_LOAN_STATUS_DETAIL_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_STATUS_DETAIL ON SC_CREDIT.TA_LOAN_STATUS_DETAIL(
   FI_REGISTRATION_NUMBER,
   FI_ADMIN_CENTER_ID,
   FI_LOAN_ID
);

-- From TA_LOAN_STATUS_DETAIL_CRT_INDEX_HU-00001.xml
CREATE INDEX SC_CREDIT.IX01_LOAN_STATUS_DETAIL ON SC_CREDIT.TA_LOAN_STATUS_DETAIL(
   FI_ADMIN_CENTER_ID,
   FI_LOAN_ID,
   FI_PAYMENT_NUMBER_ID,
   FI_ON_OFF
);

-- From TA_LOAN_STATUS_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_STATUS_DETAIL
ADD
   CONSTRAINT PK_LOAN_STATUS_DETAIL PRIMARY KEY (
      FI_REGISTRATION_NUMBER,
      FI_ADMIN_CENTER_ID,
      FI_LOAN_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_STATUS_DETAIL;

-- From TA_LOAN_STATUS_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_STATUS_DETAIL
ADD
   CONSTRAINT FK_LOAN_STATUS_DETAIL_01 FOREIGN KEY (
      FI_LOAN_STATUS_ID
   ) REFERENCES SC_CREDIT.TC_LOAN_STATUS (
      FI_LOAN_STATUS_ID
   );

-- From TA_LOAN_STATUS_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_STATUS_DETAIL
ADD
   CONSTRAINT FK_LOAN_STATUS_DETAIL_02 FOREIGN KEY (
      FI_ACTION_DETAIL_ID,
      FI_LOAN_STATUS_ID
   ) REFERENCES SC_CREDIT.TC_ACTION_DETAIL (
      FI_ACTION_DETAIL_ID,
      FI_LOAN_STATUS_ID
   );

