-- From TA_LOAN_OPERATION_DETAIL_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_OPERATION_DETAIL (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_OPERATION_ID NUMBER(15) NOT NULL,
   FI_LOAN_CONCEPT_ID NUMBER(5) NOT NULL,
   FN_ITEM_AMOUNT NUMBER(12, 2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_OPERATION_DETAIL_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_DETAIL.FI_LOAN_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_DETAIL.FI_ADMIN_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_DETAIL.FI_LOAN_OPERATION_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_DETAIL.FI_LOAN_CONCEPT_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_DETAIL.FN_ITEM_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_DETAIL.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_DETAIL.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_OPERATION_DETAIL.FD_MODIFICATION_DATE IS '';

-- From TA_LOAN_OPERATION_DETAIL_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_OPERATION_DETAIL ON SC_CREDIT.TA_LOAN_OPERATION_DETAIL(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_LOAN_OPERATION_ID,
   FI_LOAN_CONCEPT_ID
);

-- From TA_LOAN_OPERATION_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_DETAIL
ADD
   CONSTRAINT PK_LOAN_OPERATION_DETAIL PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_LOAN_OPERATION_ID,
      FI_LOAN_CONCEPT_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_OPERATION_DETAIL;

-- From TA_LOAN_OPERATION_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_DETAIL
ADD
   CONSTRAINT FK_LOAN_OPERATION_DETAIL_01 FOREIGN KEY (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_OPERATION_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_OPERATION_DETAIL
ADD
   CONSTRAINT FK_LOAN_OPERATION_DETAIL_02 FOREIGN KEY (
      FI_LOAN_CONCEPT_ID
   ) REFERENCES SC_CREDIT.TC_LOAN_CONCEPT (
      FI_LOAN_CONCEPT_ID
   );

