-- From TA_LOAN_CANCELLATION_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_CANCELLATION (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_OPERATION_ID NUMBER(15) NOT NULL,
   FI_CANCELLATION_TYPE_ID NUMBER(3) NOT NULL,
   FD_CANCELLATION date NOT NULL,
   FC_REASON VARCHAR2(255),
   FI_TRANSACTION NUMBER(33) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FC_DEVICE VARCHAR2(50) DEFAULT 'DEVICE0',
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_CANCELLATION_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_CANCELLATION ON SC_CREDIT.TA_LOAN_CANCELLATION(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_LOAN_OPERATION_ID
) TABLESPACE USERS;

-- From TA_LOAN_CANCELLATION_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_CANCELLATION
ADD
   CONSTRAINT PK_LOAN_CANCELLATION PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_LOAN_OPERATION_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_CANCELLATION;

-- From TA_LOAN_CANCELLATION_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_CANCELLATION
ADD
   CONSTRAINT FK_LOAN_CANCELLATION_03 FOREIGN KEY (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN_OPERATION (
      FI_LOAN_OPERATION_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_CANCELLATION_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_CANCELLATION
ADD
   CONSTRAINT FK_LOAN_CANCELLATION_01 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_LOAN_CANCELLATION_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_CANCELLATION
ADD
   CONSTRAINT FK_LOAN_CANCELLATION_02 FOREIGN KEY (
      FI_CANCELLATION_TYPE_ID
   ) REFERENCES SC_CREDIT.TC_CANCELLATION_TYPE (
      FI_CANCELLATION_TYPE_ID
   );

