-- From TA_LOAN_SCORING_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_LOAN_SCORING (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FN_AMOUNT NUMBER(12, 2) NOT NULL,
   FN_BALANCE NUMBER(12, 2) NOT NULL,
   FI_NUMBER_OF_PAYMENTS NUMBER(5) NOT NULL,
   FN_PAYMENT_AMOUNT NUMBER(12, 2) NOT NULL,
   FN_TOTAL_PAYED NUMBER(12, 2) NOT NULL,
   FN_PERCENTAGE NUMBER(5, 2) NOT NULL,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL,
   FC_DEVICE_ID VARCHAR2(50) NOT NULL,
   FC_IP_ADDRESS VARCHAR2(39) DEFAULT '127.0.0.1' NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_LOAN_SCORING_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FI_LOAN_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FI_ADMIN_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FN_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FN_BALANCE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FI_NUMBER_OF_PAYMENTS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FN_PAYMENT_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FN_TOTAL_PAYED IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FN_PERCENTAGE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FC_UUID_TRACKING IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FC_DEVICE_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FC_IP_ADDRESS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_LOAN_SCORING.FD_MODIFICATION_DATE IS '';

-- From TA_LOAN_SCORING_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_SCORING ON SC_CREDIT.TA_LOAN_SCORING(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID
);

-- From TA_LOAN_SCORING_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_SCORING
ADD
   CONSTRAINT PK_LOAN_SCORING PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_SCORING;

-- From TA_LOAN_SCORING_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_LOAN_SCORING
ADD
   CONSTRAINT FK_LOAN_SCORING_01 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

