-- From TA_PAYMENT_SCHEDULE_FEE_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE (
   FI_PAYMENT_SCHEDULE_ID NUMBER(3) NOT NULL,
   FI_FEE_SEQ NUMBER(3) NOT NULL,
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_CONCEPT_ID NUMBER(5) NOT NULL,
   FN_FEE_AMOUNT NUMBER(12, 2) NOT NULL,
   FN_FEE_PAYMENT_BALANCE NUMBER(12, 2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_PAYMENT_SCHEDULE_FEE_CRTB_HU-00001.xml
COMMENT ON TABLE SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE IS 'Catalog of Possible subterms';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE.FI_PAYMENT_SCHEDULE_ID IS 'Payment Number ID';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE.FI_FEE_SEQ IS 'Sequence of fees in the period';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE.FI_LOAN_ID IS 'Description of the record';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE.FI_ADMIN_CENTER_ID IS 'Loan Admin Center';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE.FI_LOAN_CONCEPT_ID IS 'Period Concept';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE.FN_FEE_AMOUNT IS 'Fee payment Amount';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE.FN_FEE_PAYMENT_BALANCE IS 'Fee balance payment amount';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE.FD_MODIFICATION_DATE IS '';

-- From TA_PAYMENT_SCHEDULE_FEE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_PAYMENT_SCHEDULE_FEE ON SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE(
   FI_PAYMENT_SCHEDULE_ID,
   FI_FEE_SEQ,
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID
);

-- From TA_PAYMENT_SCHEDULE_FEE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE
ADD
   CONSTRAINT PK_PAYMENT_SCHEDULE_FEE PRIMARY KEY (
      FI_PAYMENT_SCHEDULE_ID,
      FI_FEE_SEQ,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) USING INDEX SC_CREDIT.IXPK_PAYMENT_SCHEDULE_FEE;

-- From TA_PAYMENT_SCHEDULE_FEE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PAYMENT_SCHEDULE_FEE
ADD
   CONSTRAINT FK_PAYMENT_SCHEDULE_FEE FOREIGN KEY (
      FI_ADMIN_CENTER_ID,
      FI_PAYMENT_SCHEDULE_ID,
      FI_LOAN_ID
   ) REFERENCES SC_CREDIT.TA_PAYMENT_SCHEDULE (
      FI_PAYMENT_SCHEDULE_ID,
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

