-- From TA_PWO_AMOUNT_DETAIL_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_PWO_AMOUNT_DETAIL (
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FN_PAY_OFF_AMOUNT NUMBER(12, 2) NOT NULL,
   FN_PWO_EXT_PAYMENT NUMBER(12, 2) NOT NULL,
   FN_AMOUNT_PAID NUMBER(12, 2),
   FN_PWO_MIN_PAYMENT NUMBER(12, 2),
   FI_ADD_EXTENSION NUMBER(3) NOT NULL,
   FD_PWO_DATE date NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL,
   FI_LOAN_OPERATION_ID NUMBER(15) DEFAULT 0
) TABLESPACE USERS;

COMMENT ON TABLE SC_CREDIT.TA_PWO_AMOUNT_DETAIL IS 'Table containing the details of the Potential Write-Off amounts';

COMMENT ON COLUMN SC_CREDIT.TA_PWO_AMOUNT_DETAIL.FI_ADMIN_CENTER_ID IS 'Loan Management Center';

COMMENT ON COLUMN SC_CREDIT.TA_PWO_AMOUNT_DETAIL.FI_LOAN_ID IS 'Loan Identifier';

COMMENT ON COLUMN SC_CREDIT.TA_PWO_AMOUNT_DETAIL.FN_PAY_OFF_AMOUNT IS 'Amount when the loan defaults';

COMMENT ON COLUMN SC_CREDIT.TA_PWO_AMOUNT_DETAIL.FN_PWO_EXT_PAYMENT IS 'Amount of the required payment extension';

COMMENT ON COLUMN SC_CREDIT.TA_PWO_AMOUNT_DETAIL.FN_AMOUNT_PAID IS 'Amount Paid';

COMMENT ON COLUMN SC_CREDIT.TA_PWO_AMOUNT_DETAIL.FN_PWO_MIN_PAYMENT IS 'Amount Remaining to Pay';

COMMENT ON COLUMN SC_CREDIT.TA_PWO_AMOUNT_DETAIL.FI_ADD_EXTENSION IS 'Number of Extensions Added';

COMMENT ON COLUMN SC_CREDIT.TA_PWO_AMOUNT_DETAIL.FD_PWO_DATE IS 'Potential Write-Off Deadline Date';

COMMENT ON COLUMN SC_CREDIT.TA_PWO_AMOUNT_DETAIL.FI_LOAN_OPERATION_ID IS 'Loan Operation Number Identifier';

-- From TA_PWO_AMOUNT_DETAIL_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_PWO_AMOUNT_DETAIL ON SC_CREDIT.TA_PWO_AMOUNT_DETAIL(
   FI_ADMIN_CENTER_ID,
   FI_LOAN_ID
) TABLESPACE USERS;

-- From TA_PWO_AMOUNT_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PWO_AMOUNT_DETAIL
ADD
   CONSTRAINT PK_PWO_AMOUNT_DETAIL PRIMARY KEY (
      FI_ADMIN_CENTER_ID,
      FI_LOAN_ID
   ) USING INDEX SC_CREDIT.IXPK_PWO_AMOUNT_DETAIL;

-- From TA_PWO_AMOUNT_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PWO_AMOUNT_DETAIL
ADD
   CONSTRAINT FK_PWO_AMOUNT_DETAIL_01 FOREIGN KEY (
      FI_ADMIN_CENTER_ID,
      FI_LOAN_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

