-- From TA_PAYMENT_SCHEDULE_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_PAYMENT_SCHEDULE (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_PAYMENT_SCHEDULE_ID NUMBER(8) NOT NULL,
   FI_PAYMENT_NUMBER_ID NUMBER(3) NOT NULL,
   FN_PAYMENT_AMOUNT NUMBER(12, 2) NOT NULL,
   FN_PAYMENT_BALANCE NUMBER(12, 2) DEFAULT 0 NOT NULL,
   FI_SCHEDULE_TYPE_ID NUMBER(3) DEFAULT 1 NOT NULL,
   FD_DUE_DATE date NOT NULL,
   FI_PMT_SCHEDULE_STATUS_ID NUMBER(3) NOT NULL,
   FD_PAYMENT_DATE date,
   FI_STATUS NUMBER(2) DEFAULT 1 NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL,
   FI_PERIOD_DAYS NUMBER(3) DEFAULT 0.0 NOT NULL,
   FN_INTEREST_AMOUNT NUMBER(12, 2) DEFAULT 0.0 NOT NULL,
   FN_PRINCIPAL_PAYMENT_AMOUNT NUMBER(12, 2) DEFAULT 0.0 NOT NULL,
   FN_OUTSTANDING_BALANCE NUMBER(12, 2) DEFAULT 0.0 NOT NULL
) TABLESPACE USERS;

-- From TA_PAYMENT_SCHEDULE_CRTB_HU-00001.xml
COMMENT ON TABLE SC_CREDIT.TA_PAYMENT_SCHEDULE IS 'Table with the scheduled payments over a loan';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_LOAN_ID IS 'Description of the record';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_ADMIN_CENTER_ID IS 'Indicates if the record is valid or invalid';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_PAYMENT_SCHEDULE_ID IS 'ID of the record';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_PAYMENT_NUMBER_ID IS 'Id of the record';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FN_PAYMENT_AMOUNT IS 'Amount payed or to be paid in the date FD_DUE_DATE';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FN_PAYMENT_BALANCE IS 'Loan''s balance after the payment in the FD_DUE_DATE';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_SCHEDULE_TYPE_ID IS 'Catalog of scheduled type';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FD_DUE_DATE IS 'Date when the payment must be made';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_PMT_SCHEDULE_STATUS_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FD_PAYMENT_DATE IS 'Date when the payment really was done';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_STATUS IS '1-the record can be taken into account, 0-the record is not a valid one';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FD_MODIFICATION_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_PERIOD_DAYS IS 'Days in the Period';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FN_INTEREST_AMOUNT IS 'Interest Amount per Period';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FN_PRINCIPAL_PAYMENT_AMOUNT IS 'Principal amount per Period';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_SCHEDULE.FN_OUTSTANDING_BALANCE IS 'Outstanding balance';

-- From TA_PAYMENT_SCHEDULE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_PAYMENT_SCHEDULE ON SC_CREDIT.TA_PAYMENT_SCHEDULE(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_PAYMENT_SCHEDULE_ID
);

-- From TA_PAYMENT_SCHEDULE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PAYMENT_SCHEDULE
ADD
   CONSTRAINT PK_PAYMENT_SCHEDULE PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_PAYMENT_SCHEDULE_ID
   ) USING INDEX SC_CREDIT.IXPK_PAYMENT_SCHEDULE;

-- From TA_PAYMENT_SCHEDULE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PAYMENT_SCHEDULE
ADD
   CONSTRAINT FK_PAYMENT_SCHEDULE_01 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_PAYMENT_SCHEDULE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PAYMENT_SCHEDULE
ADD
   CONSTRAINT FK_PAYMENT_SCHEDULE_03 FOREIGN KEY (
      FI_SCHEDULE_TYPE_ID
   ) REFERENCES SC_CREDIT.TC_SCHEDULE_TYPE (
      FI_SCHEDULE_TYPE_ID
   );

-- From TA_PAYMENT_SCHEDULE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PAYMENT_SCHEDULE
ADD
   CONSTRAINT FK_PAYMENT_SCHEDULE_02 FOREIGN KEY (
      FI_PMT_SCHEDULE_STATUS_ID
   ) REFERENCES SC_CREDIT.TC_PAYMENT_SCHEDULE_STATUS (
      FI_PMT_SCHEDULE_STATUS_ID
   );

