-- From TA_PAYMENT_TYPE_DETAIL_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_PAYMENT_TYPE_DETAIL (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_PAYMENT_ID NUMBER(15) NOT NULL,
   FI_PAYMENT_TYPE_ID NUMBER(3) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FN_PAYMENT_AMOUNT NUMBER(15, 2) NOT NULL,
   FI_INVOICE_START NUMBER(5) NOT NULL,
   FI_INVOICE_FINAL NUMBER(5) NOT NULL,
   FI_TRANSACTION NUMBER(33) NOT NULL,
   FN_ANNUAL_INSOLUTE_RATE NUMBER(12, 2) NOT NULL,
   FN_ANNUAL_DEFAULT_RATE NUMBER(12, 2) NOT NULL,
   FN_RATE_PERIOD_WITHOUT_VAT NUMBER(12, 2) NOT NULL,
   FN_ANNUAL_RATE_WITHOUT_VAT NUMBER(12, 2) NOT NULL,
   FN_APR_WITHOUT_VAT NUMBER(12, 2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_PAYMENT_TYPE_DETAIL_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FI_LOAN_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FI_ADMIN_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FI_PAYMENT_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FI_PAYMENT_TYPE_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FI_STATUS IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FN_PAYMENT_AMOUNT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FI_INVOICE_START IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FI_INVOICE_FINAL IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FI_TRANSACTION IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FN_ANNUAL_INSOLUTE_RATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FN_ANNUAL_DEFAULT_RATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FN_RATE_PERIOD_WITHOUT_VAT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FN_ANNUAL_RATE_WITHOUT_VAT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FN_APR_WITHOUT_VAT IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_PAYMENT_TYPE_DETAIL.FD_MODIFICATION_DATE IS '';

-- From TA_PAYMENT_TYPE_DETAIL_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_PAYMENT_DETAIL ON SC_CREDIT.TA_PAYMENT_TYPE_DETAIL(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_PAYMENT_ID
);

-- From TA_PAYMENT_TYPE_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PAYMENT_TYPE_DETAIL
ADD
   CONSTRAINT PK_PAYMENTS_DETAIL PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_PAYMENT_ID
   ) USING INDEX SC_CREDIT.IXPK_PAYMENT_DETAIL;

-- From TA_PAYMENT_TYPE_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PAYMENT_TYPE_DETAIL
ADD
   CONSTRAINT FK_PAYMENTS_DETAIL_01 FOREIGN KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   ) REFERENCES SC_CREDIT.TA_LOAN (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID
   );

-- From TA_PAYMENT_TYPE_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_PAYMENT_TYPE_DETAIL
ADD
   CONSTRAINT FK_PAYMENTS_DETAIL_02 FOREIGN KEY (
      FI_PAYMENT_TYPE_ID
   ) REFERENCES SC_CREDIT.TC_PAYMENT_TYPE (
      FI_PAYMENT_TYPE_ID
   );

