-- From TA_TRAN_FOLIO_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_TRAN_FOLIO (
   FI_COUNTRY_ID NUMBER(3) NOT NULL,
   FI_CENTER_ID NUMBER(8) NOT NULL,
   FI_FOLIO_TX NUMBER(18) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_TRAN_FOLIO_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO.FI_COUNTRY_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO.FI_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO.FI_FOLIO_TX IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO.FD_MODIFICATION_DATE IS '';

