-- From TA_TMP_LOAN_PROCESS_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_TMP_LOAN_PROCESS (
   FI_LOAN_ID NUMBER(15) NOT NULL,
   FI_ADMIN_CENTER_ID NUMBER(8) NOT NULL,
   FI_PROCESS NUMBER(5) NOT NULL,
   FI_TRACK NUMBER(5) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

COMMENT ON TABLE SC_CREDIT.TA_TMP_LOAN_PROCESS IS 'Table for loans to be executed in a defined process';

COMMENT ON COLUMN SC_CREDIT.TA_TMP_LOAN_PROCESS.FI_LOAN_ID IS 'Loan Identifier';

COMMENT ON COLUMN SC_CREDIT.TA_TMP_LOAN_PROCESS.FI_ADMIN_CENTER_ID IS 'Loan Management Center';

COMMENT ON COLUMN SC_CREDIT.TA_TMP_LOAN_PROCESS.FI_PROCESS IS 'Defined process Number';

COMMENT ON COLUMN SC_CREDIT.TA_TMP_LOAN_PROCESS.FI_TRACK IS 'Defined Track Number';

-- From TA_TMP_LOAN_PROCESS_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_TMP_LOAN_PROCESS ON SC_CREDIT.TA_TMP_LOAN_PROCESS(
   FI_LOAN_ID,
   FI_ADMIN_CENTER_ID,
   FI_PROCESS,
   FI_TRACK
) TABLESPACE USERS;

-- From TA_TMP_LOAN_PROCESS_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_TMP_LOAN_PROCESS
ADD
   CONSTRAINT PK_TMP_LOAN_PROCESS PRIMARY KEY (
      FI_LOAN_ID,
      FI_ADMIN_CENTER_ID,
      FI_PROCESS,
      FI_TRACK
   ) USING INDEX SC_CREDIT.IXPK_TMP_LOAN_PROCESS;

