-- From TA_TRAN_FOLIO_DETAIL_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TA_TRAN_FOLIO_DETAIL (
   FI_COUNTRY_ID NUMBER(3) NOT NULL,
   FI_CENTER_ID NUMBER(8) NOT NULL,
   FI_FOLIO_TX NUMBER(18) NOT NULL,
   FD_SOLICITUD date NOT NULL,
   FC_UUID_TRACKING VARCHAR2(36) NOT NULL,
   FC_GPS_LATITUDE VARCHAR2(15) NOT NULL,
   FC_GPS_LONGITUDE VARCHAR2(15) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TA_TRAN_FOLIO_DETAIL_CRTB_HU-00001.xml
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO_DETAIL.FI_COUNTRY_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO_DETAIL.FI_CENTER_ID IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO_DETAIL.FI_FOLIO_TX IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO_DETAIL.FD_SOLICITUD IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO_DETAIL.FC_UUID_TRACKING IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO_DETAIL.FC_GPS_LATITUDE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO_DETAIL.FC_GPS_LONGITUDE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO_DETAIL.FC_USER IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO_DETAIL.FD_CREATED_DATE IS '';
COMMENT ON COLUMN SC_CREDIT.TA_TRAN_FOLIO_DETAIL.FD_MODIFICATION_DATE IS '';

-- From TA_TRAN_FOLIO_DETAIL_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_TRAN_FOLIO_DETAIL ON SC_CREDIT.TA_TRAN_FOLIO_DETAIL(
   FI_COUNTRY_ID,
   FI_CENTER_ID,
   FI_FOLIO_TX
);

-- From TA_TRAN_FOLIO_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TA_TRAN_FOLIO_DETAIL
ADD
   CONSTRAINT PK_TRAN_FOLIO_DETAIL PRIMARY KEY (
      FI_COUNTRY_ID,
      FI_CENTER_ID,
      FI_FOLIO_TX
   ) USING INDEX SC_CREDIT.IXPK_TRAN_FOLIO_DETAIL;

