-- From TC_ACCRUED_TYPE_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_ACCRUED_TYPE (
   FI_ACCRUED_TYPE_ID NUMBER(5) NOT NULL,
   FC_ACCRUED_TYPE_DESC VARCHAR2(30) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_ACCRUED_TYPE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_ACCRUED_TYPE ON SC_CREDIT.TC_ACCRUED_TYPE(
   FI_ACCRUED_TYPE_ID
) TABLESPACE USERS;

-- From TC_ACCRUED_TYPE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_ACCRUED_TYPE
ADD
   CONSTRAINT PK_ACCRUED_TYPE PRIMARY KEY (
      FI_ACCRUED_TYPE_ID
   ) USING INDEX SC_CREDIT.IXPK_ACCRUED_TYPE;

