-- From TC_ACTION_DETAIL_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_ACTION_DETAIL (
   FI_ACTION_DETAIL_ID NUMBER(3) NOT NULL,
   FI_LOAN_STATUS_ID NUMBER(5) NOT NULL,
   FC_ACTION_DETAIL_DESC VARCHAR2(100) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

COMMENT ON TABLE SC_CREDIT.TC_ACTION_DETAIL IS 'Catalog of Possible Actions that Trigger Each Status';

COMMENT ON COLUMN SC_CREDIT.TC_ACTION_DETAIL.FI_ACTION_DETAIL_ID IS 'Action Identifier';

COMMENT ON COLUMN SC_CREDIT.TC_ACTION_DETAIL.FI_LOAN_STATUS_ID IS 'Status Identifier';

COMMENT ON COLUMN SC_CREDIT.TC_ACTION_DETAIL.FC_ACTION_DETAIL_DESC IS 'Action Description';

-- From TC_ACTION_DETAIL_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_ACTION_DETAIL ON SC_CREDIT.TC_ACTION_DETAIL(
   FI_ACTION_DETAIL_ID,
   FI_LOAN_STATUS_ID
) TABLESPACE USERS;

-- From TC_ACTION_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_ACTION_DETAIL
ADD
   CONSTRAINT PK_ACTION_DETAIL PRIMARY KEY (
      FI_ACTION_DETAIL_ID,
      FI_LOAN_STATUS_ID
   ) USING INDEX SC_CREDIT.IXPK_ACTION_DETAIL;

-- From TC_ACTION_DETAIL_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_ACTION_DETAIL
ADD
   CONSTRAINT FK_ACTION_DETAIL_01 FOREIGN KEY (
      FI_LOAN_STATUS_ID
   ) REFERENCES SC_CREDIT.TC_LOAN_STATUS (
      FI_LOAN_STATUS_ID
   );

