-- From TC_ALLOWED_PERIOD_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_ALLOWED_PERIOD (
   FI_ALLOWED_PERIOD_ID NUMBER(3) NOT NULL,
   FC_ALLOWED_PERIOD_DESC VARCHAR2(5) NOT NULL,
   FI_STATUS NUMBER(2) DEFAULT 1 NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

COMMENT ON COLUMN SC_CREDIT.TC_ALLOWED_PERIOD.FI_ALLOWED_PERIOD_ID IS 'Allowed period identifier';

COMMENT ON COLUMN SC_CREDIT.TC_ALLOWED_PERIOD.FC_ALLOWED_PERIOD_DESC IS 'Allowed period desription';

COMMENT ON COLUMN SC_CREDIT.TC_ALLOWED_PERIOD.FI_STATUS IS 'Status that indicates whether the record is active or deleted';

COMMENT ON COLUMN SC_CREDIT.TC_ALLOWED_PERIOD.FC_USER IS 'Modification user';

COMMENT ON COLUMN SC_CREDIT.TC_ALLOWED_PERIOD.FD_CREATED_DATE IS 'Created date';

COMMENT ON COLUMN SC_CREDIT.TC_ALLOWED_PERIOD.FD_MODIFICATION_DATE IS 'Modification date';

-- From TC_ALLOWED_PERIOD_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_ALLOWED_PERIOD ON SC_CREDIT.TC_ALLOWED_PERIOD(
   FI_ALLOWED_PERIOD_ID
) TABLESPACE USERS;

-- From TC_ALLOWED_PERIOD_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_ALLOWED_PERIOD
ADD
   CONSTRAINT PK_ALLOWED_PERIOD PRIMARY KEY (
      FI_ALLOWED_PERIOD_ID
   ) USING INDEX SC_CREDIT.IXPK_ALLOWED_PERIOD;

