-- From TC_BALANCE_CATEGORY_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_BALANCE_CATEGORY (
   FI_BALANCE_CATEGORY_ID NUMBER(3) NOT NULL,
   FC_BALANCE_CATEGORY_DESC VARCHAR2(50) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_BALANCE_CATEGORY_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_BALANCE_CATEGORY ON SC_CREDIT.TC_BALANCE_CATEGORY(
   FI_BALANCE_CATEGORY_ID
) TABLESPACE USERS;

-- From TC_BALANCE_CATEGORY_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_BALANCE_CATEGORY
ADD
   CONSTRAINT PK_BALANCE_CATEGORY PRIMARY KEY (
      FI_BALANCE_CATEGORY_ID
   ) USING INDEX SC_CREDIT.IXPK_BALANCE_CATEGORY;

