-- From TC_BUSINESS_UNIT_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_BUSINESS_UNIT (
   FI_BUSINESS_UNIT_ID NUMBER(5) NOT NULL,
   FI_COMPANY_ID NUMBER(3) NOT NULL,
   FI_COUNTRY_ID NUMBER(3) NOT NULL,
   FC_BUSINESS_DESC VARCHAR2(50) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_BUSINESS_UNIT_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_BUSINESS_UNIT ON SC_CREDIT.TC_BUSINESS_UNIT(
   FI_BUSINESS_UNIT_ID,
   FI_COMPANY_ID,
   FI_COUNTRY_ID
) TABLESPACE USERS;

-- From TC_BUSINESS_UNIT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_BUSINESS_UNIT
ADD
   CONSTRAINT PK_BUSSINESS_UNIT PRIMARY KEY (
      FI_BUSINESS_UNIT_ID,
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   ) USING INDEX SC_CREDIT.IXPK_BUSINESS_UNIT;

-- From TC_BUSINESS_UNIT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_BUSINESS_UNIT
ADD
   CONSTRAINT FK_BUSINESS_UNIT_01 FOREIGN KEY (
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   ) REFERENCES SC_CREDIT.TC_COMPANY (
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   );

