-- From TC_COMPANY_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_COMPANY (
   FI_COMPANY_ID NUMBER(3) NOT NULL,
   FI_COUNTRY_ID NUMBER(3) NOT NULL,
   FC_COMPANY_NAME VARCHAR2(50) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_COMPANY_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_COMPANY ON SC_CREDIT.TC_COMPANY(
   FI_COMPANY_ID,
   FI_COUNTRY_ID
) TABLESPACE USERS;

-- From TC_COMPANY_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_COMPANY
ADD
   CONSTRAINT PK_COMPANY PRIMARY KEY (
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   ) USING INDEX SC_CREDIT.IXPK_COMPANY;

-- From TC_COMPANY_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_COMPANY
ADD
   CONSTRAINT FK_COMPANY_01 FOREIGN KEY (FI_COUNTRY_ID) REFERENCES SC_CREDIT.TC_COUNTRY (FI_COUNTRY_ID);

