-- From TC_COUNTRY_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_COUNTRY (
   FI_COUNTRY_ID NUMBER(3) NOT NULL,
   FC_COUNTRY_NAME VARCHAR2(60) NOT NULL,
   FC_COUNTRY_CODE VARCHAR2(3) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_COUNTRY_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_TC_COUNTRY ON SC_CREDIT.TC_COUNTRY(FI_COUNTRY_ID) TABLESPACE USERS;

-- From TC_COUNTRY_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_COUNTRY
ADD
   CONSTRAINT PK_COUNTRY PRIMARY KEY (FI_COUNTRY_ID) USING INDEX SC_CREDIT.IXPK_TC_COUNTRY;

