-- From TC_CENTER_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_CENTER (
   FI_CENTER_ID NUMBER(8) NOT NULL,
   FI_BUSINESS_UNIT_ID NUMBER(5) NOT NULL,
   FI_COMPANY_ID NUMBER(3) NOT NULL,
   FI_COUNTRY_ID NUMBER(3) NOT NULL,
   FC_CENTER_NAME VARCHAR2(80) NOT NULL,
   FI_REGION_ID NUMBER(10) NOT NULL,
   FI_TERRITORY_ID NUMBER(10) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_CENTER_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_CENTER ON SC_CREDIT.TC_CENTER(
   FI_CENTER_ID,
   FI_BUSINESS_UNIT_ID,
   FI_COMPANY_ID,
   FI_COUNTRY_ID
) TABLESPACE USERS;

-- From TC_CENTER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_CENTER
ADD
   CONSTRAINT PK_TC_CENTER PRIMARY KEY (
      FI_CENTER_ID,
      FI_BUSINESS_UNIT_ID,
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   ) USING INDEX SC_CREDIT.IXPK_CENTER;

-- From TC_CENTER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_CENTER
ADD
   CONSTRAINT FK_CENTER01 FOREIGN KEY (
      FI_BUSINESS_UNIT_ID,
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   ) REFERENCES SC_CREDIT.TC_BUSINESS_UNIT (
      FI_BUSINESS_UNIT_ID,
      FI_COMPANY_ID,
      FI_COUNTRY_ID
   );

