-- From TC_CONCEPT_EXPRESSION_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_CONCEPT_EXPRESSION (
   FI_CONCEPT_EXPRESSION_ID NUMBER(3) NOT NULL,
   FC_CONCEPT_EXPRESSION_DESC VARCHAR2(50) NOT NULL,
   FI_STATUS NUMBER(2) DEFAULT 1 NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

COMMENT ON COLUMN SC_CREDIT.TC_CONCEPT_EXPRESSION.FI_CONCEPT_EXPRESSION_ID IS 'Concept expression identifier';

COMMENT ON COLUMN SC_CREDIT.TC_CONCEPT_EXPRESSION.FC_CONCEPT_EXPRESSION_DESC IS 'Concetp expression desc';

COMMENT ON COLUMN SC_CREDIT.TC_CONCEPT_EXPRESSION.FI_STATUS IS 'Status that indicates whether the record is active or deleted';

COMMENT ON COLUMN SC_CREDIT.TC_CONCEPT_EXPRESSION.FC_USER IS 'Modification user';

COMMENT ON COLUMN SC_CREDIT.TC_CONCEPT_EXPRESSION.FD_CREATED_DATE IS 'Creation date';

COMMENT ON COLUMN SC_CREDIT.TC_CONCEPT_EXPRESSION.FD_MODIFICATION_DATE IS 'Modification date';

-- From TC_CONCEPT_EXPRESSION_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_CONCEPT_EXPRESSION ON SC_CREDIT.TC_CONCEPT_EXPRESSION(
   FI_CONCEPT_EXPRESSION_ID
) TABLESPACE USERS;

-- From TC_CONCEPT_EXPRESSION_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_CONCEPT_EXPRESSION
ADD
   CONSTRAINT PK_CONCEPT_EXPRESSION PRIMARY KEY (
      FI_CONCEPT_EXPRESSION_ID
   ) USING INDEX SC_CREDIT.IXPK_CONCEPT_EXPRESSION;

