-- From TC_LOAN_STATUS_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_LOAN_STATUS (
   FI_LOAN_STATUS_ID NUMBER(5) NOT NULL,
   FC_LOAN_STATUS_DESC VARCHAR2(50) NOT NULL,
   FC_ACRONYM VARCHAR2(20),
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_LOAN_STATUS_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.PK_TC_LOAN_STATUS ON SC_CREDIT.TC_LOAN_STATUS(
   FI_LOAN_STATUS_ID
) TABLESPACE USERS;

-- From TC_LOAN_STATUS_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_LOAN_STATUS
ADD
   CONSTRAINT PK_TC_LOAN_STATUS PRIMARY KEY (
      FI_LOAN_STATUS_ID
   ) USING INDEX SC_CREDIT.PK_TC_LOAN_STATUS;

