-- From TC_LOAN_CONCEPT_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_LOAN_CONCEPT (
   FI_LOAN_CONCEPT_ID NUMBER(5) NOT NULL,
   FC_LOAN_CONCEPT_DESC VARCHAR2(60) NOT NULL,
   FI_LOAN_CONCEPT_TYPE_ID NUMBER(5) NOT NULL,
   FC_KEY VARCHAR2(40),
   FI_BALANCE_CATEGORY_ID NUMBER(3) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_LOAN_CONCEPT_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_CONCEPT ON SC_CREDIT.TC_LOAN_CONCEPT(
   FI_LOAN_CONCEPT_ID
) TABLESPACE USERS;

-- From TC_LOAN_CONCEPT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_LOAN_CONCEPT
ADD
   CONSTRAINT PK_LOAN_CONCEPT PRIMARY KEY (
      FI_LOAN_CONCEPT_ID
   ) USING INDEX SC_CREDIT.IXPK_LOAN_CONCEPT;

-- From TC_LOAN_CONCEPT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_LOAN_CONCEPT
ADD
   CONSTRAINT FK_LOAN_CONCEPT_01 FOREIGN KEY (
      FI_LOAN_CONCEPT_TYPE_ID
   ) REFERENCES SC_CREDIT.TC_LOAN_CONCEPT_TYPE (
      FI_LOAN_CONCEPT_TYPE_ID
   );

-- From TC_LOAN_CONCEPT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_LOAN_CONCEPT
ADD
   CONSTRAINT FK_LOAN_CONCEPT_02 FOREIGN KEY (
      FI_BALANCE_CATEGORY_ID
   ) REFERENCES SC_CREDIT.TC_BALANCE_CATEGORY (
      FI_BALANCE_CATEGORY_ID
   );

