-- From TC_LOAN_MISCELLAN_OPERATIONS_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_LOAN_MISCELLAN_OPERATIONS (
   FI_MISCELLAN_OPERATIONS_ID NUMBER(3) NOT NULL,
   FC_MISCELLAN_OPERATIONS VARCHAR2(50) NOT NULL,
   FI_STATUS NUMBER(2) DEFAULT 1 NOT NULL,
   FC_USER VARCHAR2(30) NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_LOAN_MISCELLAN_OPERATIONS_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_MISCELLAN_OPERATIONS ON SC_CREDIT.TC_LOAN_MISCELLAN_OPERATIONS(
   FI_MISCELLAN_OPERATIONS_ID
) TABLESPACE USERS;

-- From TC_LOAN_MISCELLAN_OPERATIONS_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_LOAN_MISCELLAN_OPERATIONS
ADD
   CONSTRAINT PK_MISCELLAN_OPERATIONS PRIMARY KEY (
      FI_MISCELLAN_OPERATIONS_ID
   ) USING INDEX SC_CREDIT.IXPK_MISCELLAN_OPERATIONS;

