-- From TC_LOAN_STATUS_TRIGGER_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_LOAN_STATUS_TRIGGER (
   FI_LOAN_STATUS_ID NUMBER(5) NOT NULL,
   FI_TRIGGER_ID NUMBER(3) NOT NULL,
   FI_NEXT_STATUS NUMBER(5) NOT NULL,
   FI_IS_TRIGGERS NUMBER(1),
   FI_IS_STAY_DAY NUMBER(1),
   FI_STAY_DAY NUMBER(5),
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_LOAN_STATUS_TRIGGER_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_LOAN_TRIGGER ON SC_CREDIT.TC_LOAN_STATUS_TRIGGER(
   FI_LOAN_STATUS_ID,
   FI_TRIGGER_ID,
   FI_NEXT_STATUS
) TABLESPACE USERS;

-- From TC_LOAN_STATUS_TRIGGER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_LOAN_STATUS_TRIGGER
ADD
   CONSTRAINT PK_LOAN_TRIGGER PRIMARY KEY (
      FI_LOAN_STATUS_ID,
      FI_TRIGGER_ID,
      FI_NEXT_STATUS
   ) USING INDEX SC_CREDIT.IXPK_LOAN_TRIGGER;

-- From TC_LOAN_STATUS_TRIGGER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_LOAN_STATUS_TRIGGER
ADD
   CONSTRAINT FK_LOAN_STATUS_TRIGGER_01 FOREIGN KEY (
      FI_LOAN_STATUS_ID
   ) REFERENCES SC_CREDIT.TC_LOAN_STATUS (
      FI_LOAN_STATUS_ID
   );

-- From TC_LOAN_STATUS_TRIGGER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_LOAN_STATUS_TRIGGER
ADD
   CONSTRAINT FK_LOAN_STATUS_TRIGGER_02 FOREIGN KEY (FI_TRIGGER_ID) REFERENCES SC_CREDIT.TC_TRIGGER (FI_TRIGGER_ID);

