-- From TC_OPERATION_SIGN_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_OPERATION_SIGN (
   FI_OPERATION_SIGN_ID NUMBER(2) NOT NULL,
   FI_OPERATION_SIGN NUMBER(2) NOT NULL,
   FC_OPERATION_SIGN_DESC VARCHAR2(60) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_OPERATION_SIGN_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_OPERATION_SIGN ON SC_CREDIT.TC_OPERATION_SIGN(
   FI_OPERATION_SIGN_ID
) TABLESPACE USERS;

-- From TC_OPERATION_SIGN_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_OPERATION_SIGN
ADD
   CONSTRAINT PK_OPERATION_SIGN PRIMARY KEY (
      FI_OPERATION_SIGN_ID
   ) USING INDEX SC_CREDIT.IXPK_OPERATION_SIGN;

