-- From TC_OPERATION_TYPE_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_OPERATION_TYPE (
   FI_OPERATION_TYPE_ID NUMBER(5) NOT NULL,
   FC_OPERATION_TYPE_DESC VARCHAR2(80) NOT NULL,
   FI_LOAN_STATUS_ID NUMBER(5),
   FI_OPERATION_SIGN_ID NUMBER(2) NOT NULL,
   FI_CONCEPT_VOID NUMBER(5) DEFAULT 0 NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_OPERATION_TYPE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_OPERATION_TYPE ON SC_CREDIT.TC_OPERATION_TYPE(
   FI_OPERATION_TYPE_ID
) TABLESPACE USERS;

-- From TC_OPERATION_TYPE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_OPERATION_TYPE
ADD
   CONSTRAINT PK_OPERATION_TYPE PRIMARY KEY (
      FI_OPERATION_TYPE_ID
   ) USING INDEX SC_CREDIT.IXPK_OPERATION_TYPE;

-- From TC_OPERATION_TYPE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_OPERATION_TYPE
ADD
   CONSTRAINT FK_OPERATION_TYPE_01 FOREIGN KEY (
      FI_OPERATION_SIGN_ID
   ) REFERENCES SC_CREDIT.TC_OPERATION_SIGN (
      FI_OPERATION_SIGN_ID
   );

