-- From TC_PAYMENT_TENDER_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_PAYMENT_TENDER (
   FI_TENDER_TYPE_ID NUMBER(4) NOT NULL,
   FC_PAYMENT_TENDER_DESC VARCHAR2(60) NOT NULL,
   FI_CENTER_ID NUMBER(8) NOT NULL,
   FI_STATUS NUMBER(2) DEFAULT 1 NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_PAYMENT_TENDER_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_PAYMENT_TENDER ON SC_CREDIT.TC_PAYMENT_TENDER(
   FI_TENDER_TYPE_ID
) TABLESPACE USERS;

-- From TC_PAYMENT_TENDER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_PAYMENT_TENDER
ADD
   CONSTRAINT PK_PAYMENT_TENDER PRIMARY KEY (
      FI_TENDER_TYPE_ID
   ) USING INDEX SC_CREDIT.IXPK_PAYMENT_TENDER;

-- From TC_PAYMENT_TENDER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_PAYMENT_TENDER
ADD
   CONSTRAINT FK_PAYMENT_TENDER_01 FOREIGN KEY (
      FI_TENDER_TYPE_ID
   ) REFERENCES SC_CREDIT.TC_TENDER_TYPE (
      FI_TENDER_TYPE_ID
   );

