-- From TC_PAYMENT_SCHEDULE_STATUS_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_PAYMENT_SCHEDULE_STATUS (
   FI_PMT_SCHEDULE_STATUS_ID NUMBER(3) NOT NULL,
   FI_PMT_SCHEDULE_STATUS_DESC VARCHAR2(30) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_PAYMENT_SCHEDULE_STATUS_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_PAYMENT_SCHEDULE_STATUS ON SC_CREDIT.TC_PAYMENT_SCHEDULE_STATUS(
   FI_PMT_SCHEDULE_STATUS_ID
) TABLESPACE USERS;

-- From TC_PAYMENT_SCHEDULE_STATUS_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_PAYMENT_SCHEDULE_STATUS
ADD
   CONSTRAINT PK_PAYMENT_SCHEDULE_STATUS PRIMARY KEY (
      FI_PMT_SCHEDULE_STATUS_ID
   ) USING INDEX SC_CREDIT.IXPK_PAYMENT_SCHEDULE_STATUS;

