-- From TC_PRODUCT_CRTB_HU-00001.xml
CREATE TABLE sc_credit.TC_PRODUCT (
   FI_PRODUCT_ID NUMBER(10) NOT NULL,
   FI_COUNTRY_ID NUMBER(3),
   FI_COMPANY_ID NUMBER(3),
   FC_PRODUCT_NAME VARCHAR2(50),
   FC_PRODUCT_DESC VARCHAR2(150),
   FD_RELEASE_DATE date,
   FC_PRODUCT_ADAPTER_ID VARCHAR2(32),
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_PRODUCT_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX sc_credit.IXPK_PRODUCT ON sc_credit.TC_PRODUCT(FI_PRODUCT_ID) TABLESPACE USERS;

-- From TC_PRODUCT_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   sc_credit.TC_PRODUCT
ADD
   CONSTRAINT PK_PRODUCT PRIMARY KEY (FI_PRODUCT_ID) USING INDEX sc_credit.IXPK_PRODUCT;

