-- From TC_SUBTERM_TYPE_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_SUBTERM_TYPE (
   FI_SUBTERM_TYPE_ID NUMBER(5) NOT NULL,
   FC_SUBTERM_TYPE_DESC VARCHAR2(60) NOT NULL,
   FI_STATUS NUMBER(2) DEFAULT 1 NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

COMMENT ON TABLE SC_CREDIT.TC_SUBTERM_TYPE IS 'Catalog of Possible subterms';

COMMENT ON COLUMN SC_CREDIT.TC_SUBTERM_TYPE.FI_SUBTERM_TYPE_ID IS 'ID to identify the subterms';

COMMENT ON COLUMN SC_CREDIT.TC_SUBTERM_TYPE.FC_SUBTERM_TYPE_DESC IS 'Description subterm type';

COMMENT ON COLUMN SC_CREDIT.TC_SUBTERM_TYPE.FI_STATUS IS 'On/Off Indicator';

-- From TC_SUBTERM_TYPE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_SUBTERM_TYPE ON SC_CREDIT.TC_SUBTERM_TYPE(
   FI_SUBTERM_TYPE_ID
) TABLESPACE USERS;

-- From TC_SUBTERM_TYPE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_SUBTERM_TYPE
ADD
   CONSTRAINT PK_SUBTERM_TYPE PRIMARY KEY (
      FI_SUBTERM_TYPE_ID
   ) USING INDEX SC_CREDIT.IXPK_SUBTERM_TYPE;

