-- From TC_SCHEDULE_TYPE_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_SCHEDULE_TYPE (
   FI_SCHEDULE_TYPE_ID NUMBER(3) NOT NULL,
   FC_SCHEDULE_TYPE_DESC VARCHAR2(60) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

COMMENT ON TABLE SC_CREDIT.TC_SCHEDULE_TYPE IS 'Catalog kinds of payment schedule''s';

COMMENT ON COLUMN SC_CREDIT.TC_SCHEDULE_TYPE.FI_SCHEDULE_TYPE_ID IS 'ID of the record';

COMMENT ON COLUMN SC_CREDIT.TC_SCHEDULE_TYPE.FC_SCHEDULE_TYPE_DESC IS 'Description of the record';

COMMENT ON COLUMN SC_CREDIT.TC_SCHEDULE_TYPE.FI_STATUS IS 'Indicates if the record is valid or invalid';

-- From TC_SCHEDULE_TYPE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_SCHEDULE_TYPE ON SC_CREDIT.TC_SCHEDULE_TYPE(
   FI_SCHEDULE_TYPE_ID
) TABLESPACE USERS;

-- From TC_SCHEDULE_TYPE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_SCHEDULE_TYPE
ADD
   CONSTRAINT PK_SCHEDULE_TYPE PRIMARY KEY (
      FI_SCHEDULE_TYPE_ID
   ) USING INDEX SC_CREDIT.IXPK_SCHEDULE_TYPE;

