-- From TC_TRIGGER_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_TRIGGER (
   FI_TRIGGER_ID NUMBER(3) NOT NULL,
   FC_TRIGGER_DESC VARCHAR2(100),
   FC_ACRONYM_TRIGGER VARCHAR2(10),
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_TRIGGER_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_TRIGGER ON SC_CREDIT.TC_TRIGGER(FI_TRIGGER_ID) TABLESPACE USERS;

-- From TC_TRIGGER_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_TRIGGER
ADD
   CONSTRAINT PK_TRIGGER PRIMARY KEY (FI_TRIGGER_ID) USING INDEX SC_CREDIT.IXPK_TRIGGER;

