-- From TC_TERM_TYPE_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_TERM_TYPE (
   FI_TERM_TYPE_ID NUMBER(3) NOT NULL,
   FC_TERM_TYPE_DESC VARCHAR2(30) NOT NULL,
   FI_TERM_TYPE_DAYS NUMBER(5) NOT NULL,
   FC_ADAPTER_ID VARCHAR2(10),
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_TERM_TYPE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_TERM_TYPE ON SC_CREDIT.TC_TERM_TYPE(
   FI_TERM_TYPE_ID
) TABLESPACE USERS;

-- From TC_TERM_TYPE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_TERM_TYPE
ADD
   CONSTRAINT PK_TERM_TYPE PRIMARY KEY (
      FI_TERM_TYPE_ID
   ) USING INDEX SC_CREDIT.IXPK_TERM_TYPE;

