-- From TC_TENDER_CATEGORY_TYPE_CRTB_HU-00001.xml
CREATE TABLE SC_CREDIT.TC_TENDER_CATEGORY_TYPE (
   FI_TENDER_CATEGORY_TYPE_ID NUMBER(3) NOT NULL,
   FC_TENDER_CATEGORY_TYPE_DESC VARCHAR2(255) NOT NULL,
   FI_STATUS NUMBER(2) NOT NULL,
   FC_USER VARCHAR2(30) DEFAULT USER NOT NULL,
   FD_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
   FD_MODIFICATION_DATE date DEFAULT SYSDATE NOT NULL
) TABLESPACE USERS;

-- From TC_TENDER_CATEGORY_TYPE_CRT_INDEX_HU-00001.xml
CREATE UNIQUE INDEX SC_CREDIT.IXPK_TENDER_CATEGORY_TYPE ON SC_CREDIT.TC_TENDER_CATEGORY_TYPE(
   FI_TENDER_CATEGORY_TYPE_ID
) TABLESPACE USERS;

-- From TC_TENDER_CATEGORY_TYPE_ALTB_ADD_CONST_HU-00001.xml
ALTER TABLE
   SC_CREDIT.TC_TENDER_CATEGORY_TYPE
ADD
   CONSTRAINT PK_TENDER_CATEGORY_TYPE PRIMARY KEY (
      FI_TENDER_CATEGORY_TYPE_ID
   ) USING INDEX SC_CREDIT.IXPK_TENDER_CATEGORY_TYPE;

