CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_INS_LOAN_OPERATION_VOID (
    PA_LOAN_ID               IN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_LOAN_ID%TYPE,
    PA_ADMIN_CENTER_ID       IN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_ADMIN_CENTER_ID%TYPE,
    PA_OPERATION_REQUEST_ID  IN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_OPERATION_REQUEST_ID%TYPE,
    PA_OPERATION_TYPE_ID     IN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_OPERATION_TYPE_ID%TYPE,
    PA_OPERATION_REVERSED_ID IN SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_OPERATION_REVERSED_ID%TYPE,
    PA_REVERSE_REASON        IN SC_CREDIT.TA_LOAN_OPERATION_VOID.FC_REVERSE_REASON%TYPE,
    PA_LOAN_VOID_TOKEN       IN SC_CREDIT.TA_LOAN_TOKEN_VOID.FI_LOAN_VOID_TOKEN%TYPE,
    PA_USER                  IN SC_CREDIT.TA_LOAN_OPERATION_VOID.FC_USER%TYPE,
    PA_IP_ADDRESS            IN SC_CREDIT.TA_LOAN_OPERATION_VOID.FC_IP_ADDRESS%TYPE,
    PA_UUID_TRACKING         IN SC_CREDIT.TA_LOAN_OPERATION_VOID.FC_UUID_TRACKING%TYPE,
    PA_STATUS_CODE           OUT NUMBER,
    PA_STATUS_MSG            OUT VARCHAR2
)
IS
 /* ********************************************************************
 * PROJECT: CORE LOAN
 * DESCRIPTION: PROCEDURE FOR SAVING INFORMATION OF THE OPERATION_ID WHICH
 *              REQUESTS REVERSING OTHER OPERATION_ID; AND IF IT IS THE CASE,
 *              A TOKEN IS SAVED AS WELL FOR POSTERIOR REVERSING ONCE ONE DAY
 *              HAS PASSED AFTER THE INITIAL REVERSING REQUEST.
 * PRECONDITIONS: PRE-EXISTING LOANS AND OPERATIONS
 * CREATED DATE: 06/01/2025
 * CREATOR: GILBERTO CHAVEZ MUNOZ
 * UPDATE: VICTOR DANIEL GUTIERREZ RODIRGUEZ
 ***********************************************************************/
  CSL_0            CONSTANT SIMPLE_INTEGER := 0;
  CSL_1            CONSTANT SIMPLE_INTEGER := 1;
  CSL_204          CONSTANT SIMPLE_INTEGER := 204;
  CSL_ARROW        CONSTANT VARCHAR2(5) := '->';
  CSL_JSON         CONSTANT VARCHAR2(5) := NULL;
  CSL_SUCCESS      CONSTANT VARCHAR2(8) := 'SUCCESS';
  CSL_NO_INSERTION CONSTANT VARCHAR2(20) := 'NO DATA INSERTED';
  CSL_SP           CONSTANT SIMPLE_INTEGER := 1;
  VG_LOAN_OPERATION_VOID_ID SC_CREDIT.TA_LOAN_OPERATION_VOID.FI_LOAN_OPERATION_VOID_ID%TYPE;

BEGIN



INSERT INTO SC_CREDIT.TA_LOAN_OPERATION_VOID(
    FI_LOAN_OPERATION_VOID_ID,
    FI_LOAN_ID,
    FI_ADMIN_CENTER_ID,
    FI_OPERATION_REQUEST_ID,
    FI_OPERATION_TYPE_ID,
    FI_OPERATION_REVERSED_ID,
    FC_REVERSE_REASON,
    FC_USER,
    FC_IP_ADDRESS,
    FD_CREATED_DATE,
    FD_MODIFICATION_DATE,
    FC_UUID_TRACKING)
VALUES(
          SC_CREDIT.SE_LOAN_OPERATION_VOID_ID.NEXTVAL,
          PA_LOAN_ID,
          PA_ADMIN_CENTER_ID,
          PA_OPERATION_REQUEST_ID,
          PA_OPERATION_TYPE_ID,
          PA_OPERATION_REVERSED_ID,
          PA_REVERSE_REASON,
          PA_USER,
          PA_IP_ADDRESS,
          SYSDATE,
          SYSDATE,
          PA_UUID_TRACKING)
    RETURNING FI_LOAN_OPERATION_VOID_ID INTO VG_LOAN_OPERATION_VOID_ID ;


IF PA_LOAN_VOID_TOKEN > CSL_0 THEN

            INSERT INTO SC_CREDIT.TA_LOAN_TOKEN_VOID(
                FI_LOAN_TOKEN_VOID_ID,
                FI_LOAN_OPERATION_VOID_ID,
                FI_LOAN_VOID_TOKEN,
                FC_USER,
                FC_IP_ADDRESS,
                FD_CREATED_DATE,
                FD_MODIFICATION_DATE,
                FC_UUID_TRACKING)
            VALUES(
                SC_CREDIT.SE_LOAN_TOKEN_VOID_ID.NEXTVAL,
                VG_LOAN_OPERATION_VOID_ID,
                PA_LOAN_VOID_TOKEN,
                PA_USER,
                PA_IP_ADDRESS,
                SYSDATE,
                SYSDATE,
                PA_UUID_TRACKING);

END IF;

COMMIT;
PA_STATUS_CODE := CSL_0;
        PA_STATUS_MSG  := CSL_SUCCESS;


EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    PA_STATUS_CODE := CSL_204;
    PA_STATUS_MSG := CSL_NO_INSERTION;
    PA_STATUS_CODE := SQLCODE;
    PA_STATUS_MSG := SQLERRM || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
    SC_CREDIT.SP_ERROR_LOG(
       UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_SP)
       ,SQLCODE
       ,SQLERRM
       ,DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
       ,NULL
       ,CSL_JSON
       );

END SP_INS_LOAN_OPERATION_VOID;

/

GRANT EXECUTE ON SC_CREDIT.SP_INS_LOAN_OPERATION_VOID TO USRNCPCREDIT1
/
