CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_BTC_UPD_LOAN 
   (PA_LOAN_ID            IN NUMBER
   ,PA_ADMIN_CENTER_ID    IN NUMBER
   ,PA_LOAN_STATUS_ID     IN NUMBER
   ,PA_COMMIT             IN NUMBER
   ,PA_STATUS_CODE        OUT NUMBER
   ,PA_STATUS_MSG         OUT VARCHAR2)
IS
   /* **************************************************************
   * DESCRIPTION: PROCESS TO UPDATE TABLE TA_LOAN
   * CREATED DATE: 19/11/2024
   * CREATOR: CRISTHIAN MORALES
   ************************************************************** */
    CSL_0                         CONSTANT SIMPLE_INTEGER := 0;
    CSL_1                         CONSTANT SIMPLE_INTEGER := 1;
    CSL_SP                        CONSTANT SIMPLE_INTEGER := 1;
    CSL_2002                      CONSTANT SIMPLE_INTEGER := -20002;
    CSL_ARROW                     CONSTANT VARCHAR2(20)   := '->';
    CSL_MSG_SUCCESS               CONSTANT VARCHAR2(20)   := 'SUCCESS';
    CSL_NOT_UPDATED               CONSTANT VARCHAR2(20)   := ' NOT_UPDATE ';
    CSL_TA_LOAN                   CONSTANT VARCHAR2(20)   := ' LOAN ';
    CSL_ADMIN_CENTER_ID           CONSTANT VARCHAR2(20)   := 'ADMIN_CENTER_ID';
BEGIN
   PA_STATUS_CODE := CSL_0;
   PA_STATUS_MSG  := CSL_MSG_SUCCESS;

   UPDATE SC_CREDIT.TA_LOAN LO
     SET LO.FD_LOAN_STATUS_DATE = SYSDATE
        ,LO.FD_MODIFICATION_DATE = SYSDATE
        ,LO.FI_LOAN_STATUS_ID=PA_LOAN_STATUS_ID
     WHERE LO.FI_LOAN_ID=PA_LOAN_ID
     AND LO.FI_ADMIN_CENTER_ID=PA_ADMIN_CENTER_ID;

    IF SQL%ROWCOUNT = CSL_0 THEN
     RAISE_APPLICATION_ERROR(CSL_2002, CSL_NOT_UPDATED || CSL_TA_LOAN);
    END IF;

    IF PA_COMMIT = CSL_1 THEN
      COMMIT;
    END IF;
EXCEPTION
 WHEN OTHERS THEN
    ROLLBACK;
    PA_STATUS_CODE := SQLCODE;
    PA_STATUS_MSG := SQLERRM || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;

    SC_CREDIT.SP_BATCH_ERROR_LOG(UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_SP)
                                ,SQLCODE
                                ,SQLERRM
                                ,DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
                                ,CSL_1
                                ,NULL
                                ||CSL_ADMIN_CENTER_ID ||PA_ADMIN_CENTER_ID);
END SP_BTC_UPD_LOAN;

/

GRANT EXECUTE ON SC_CREDIT.SP_BTC_UPD_LOAN TO USRNCPCREDIT1
/
GRANT EXECUTE ON SC_CREDIT.SP_BTC_UPD_LOAN TO USRBTCCREDIT1
/
