CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_ERROR_LOG (
    PA_PROCESS       IN VARCHAR2,
    PA_SQL_CODE      IN NUMBER,
    PA_ERROR_MESSAGE IN VARCHAR2,
    PA_BACKTRACE     IN VARCHAR2,
    PA_UUID_TRACKING IN VARCHAR2,
    PA_ADITIONAL_MSG IN VARCHAR2
) AS
/*************************************************************
  PROJECT    :  TRANSFORMATION
  DESCRIPTION:  PACKAGE WITH ERROR LOG
  CREATOR:      RICARDO GUTI??RREZ M.
  CREATED DATE: MAY-15-23


         this is the version 2
*************************************************************/

    CSL_1    PLS_INTEGER := 1;
    CSL_36   PLS_INTEGER := 36;
    CSL_80   PLS_INTEGER := 80;
    CSL_1000 PLS_INTEGER := 1000;
    CSL_600  PLS_INTEGER := 600;
    CSL_500  PLS_INTEGER := 500;


    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO SC_CREDIT.TA_ERROR_LOG (
        FI_LOG_ID,
        FD_ERROR,
        FC_PROCESS,
        FI_SQL_CODE,
        FC_SQL_ERRM,
        FC_BACKTRACE,
        FC_UUID_TRACKING,
        FC_ADITIONAL
    ) VALUES (
        SC_CREDIT.SE_ERROR_LOG.NEXTVAL,
        SYSDATE,
        SUBSTR(PA_PROCESS, CSL_1, CSL_80),
        PA_SQL_CODE,
        SUBSTR(PA_ERROR_MESSAGE, CSL_1, CSL_1000),
        SUBSTR(PA_BACKTRACE, CSL_1, CSL_600),
        SUBSTR( NVL(PA_UUID_TRACKING,' '),CSL_1, CSL_36 ),
        SUBSTR( NVL(PA_ADITIONAL_MSG,' ') , CSL_1, CSL_500)
    );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END SP_ERROR_LOG;


/

GRANT EXECUTE ON SC_CREDIT.SP_ERROR_LOG TO USRNCPCREDIT1
/
