CREATE OR REPLACE  TYPE SC_CREDIT.TYP_REC_BTC_BALANCE AS OBJECT ( FI_LOAN_BALANCE_ID           NUMBER(15,0), FI_ADMIN_CENTER_ID           NUMBER(8,0), FI_LOAN_ID                   NUMBER(15,0), FI_LOAN_OPERATION_ID         NUMBER(15,0), FI_BALANCE_SEQ               NUMBER(5,0), FN_PRINCIPAL_BALANCE         NUMBER(12, 2), FN_FINANCE_CHARGE_BALANCE    NUMBER(12, 2), FN_ADDITIONAL_CHARGE_BALANCE NUMBER(12, 2)
); 
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_BALANCE TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_BALANCE TO USRBTCCREDIT1;
