CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_BTC_INS_DAILY_INTEREST (
    PA_FI_LOAN_ID                   IN SC_CREDIT.TA_LOAN_INTEREST.FI_LOAN_ID%TYPE
   ,PA_FI_ADMIN_CENTER_ID           IN SC_CREDIT.TA_LOAN_INTEREST.FI_ADMIN_CENTER_ID%TYPE
   ,PA_FI_PAYMENT_NUMBER_ID         IN SC_CREDIT.TA_LOAN_INTEREST.FI_PAYMENT_NUMBER_ID%TYPE
   ,PA_FI_DAYS_ACUM_BY_TERM         IN SC_CREDIT.TA_LOAN_INTEREST.FI_DAYS_ACUM_BY_TERM%TYPE
   ,PA_FN_DAILY_INTEREST            IN SC_CREDIT.TA_LOAN_INTEREST.FN_DAILY_INTEREST%TYPE
   ,PA_FN_ACCRUED_INTEREST_BALANCE  IN SC_CREDIT.TA_LOAN_INTEREST.FN_ACCRUED_INTEREST_BALANCE%TYPE
   ,PA_FN_ACCRUED_INTEREST_LOAN     IN SC_CREDIT.TA_LOAN_INTEREST.FN_ACCRUED_INTEREST_LOAN%TYPE
   ,PA_FN_PAYMENT_INTEREST          IN SC_CREDIT.TA_LOAN_INTEREST.FI_PAYMENT_NUMBER_ID%TYPE
   ,PA_FC_CONDITION_INTEREST        IN SC_CREDIT.TA_LOAN_INTEREST.FC_CONDITION_INTEREST%TYPE
   ,PA_FD_OPERATION_DATE            IN VARCHAR2
   ,PA_FD_APPLICATION_DATE          IN VARCHAR2
   ,PA_FI_TRANSACTION               IN NUMBER
   ,PA_COMMIT                       IN NUMBER
   ,PA_STATUS_CODE                  OUT NUMBER
   ,PA_STATUS_MSG                   OUT VARCHAR2
   )
   IS

   /* **************************************************************
   * PROJECT: LOAN LIFE CYCLE
   * DESCRIPTION: V3 - PROCESS TO APPLY DAILY INTEREST
   * CREATED DATE: 10/24/2024
   * CREATOR: CRISTHIAN MORALES
   * MODIFICATION DATE: 12/23/2024
   * PERFORMANCE MODIFICATIONS - VICTOR GARCIA
   ************************************************************** */

   --CONSTANT
   CSL_ARROW             CONSTANT VARCHAR2(5)   := '->';
   CSL_0                 CONSTANT SIMPLE_INTEGER := 0;
   CSL_1                 CONSTANT SIMPLE_INTEGER := 1;
   CSL_SP                CONSTANT SIMPLE_INTEGER := 1;
   CSL_20002              CONSTANT SIMPLE_INTEGER := -20002;
   CSL_MSG_SUCCESS       CONSTANT VARCHAR2(10)   := 'SUCCESS';
   CSL_TA_LOAN_INTEREST  CONSTANT VARCHAR2(20)   := ' LOAN INTEREST ';
   CSL_COMMA             CONSTANT VARCHAR2(5) := ' , ';
   CSL_LOANID            CONSTANT VARCHAR2(10) := 'LOANID: ';
   CSL_ADMINCENTERID     CONSTANT VARCHAR2(20) := 'ADMINCENTERID: ';
   CSL_DATE_FORMAT       CONSTANT VARCHAR2(30) := 'MM/DD/YYYY hh24:mi:ss';

   BEGIN
      PA_STATUS_CODE:= CSL_0;
      PA_STATUS_MSG := CSL_MSG_SUCCESS;

      INSERT INTO SC_CREDIT.TA_LOAN_INTEREST
               (FI_LOAN_ID
               ,FI_ADMIN_CENTER_ID
               ,FI_PAYMENT_NUMBER_ID
               ,FI_DAYS_ACUM_BY_TERM
               ,FN_DAILY_INTEREST
               ,FN_ACCRUED_INTEREST_BALANCE
               ,FN_ACCRUED_INTEREST_LOAN
               ,FN_PAYMENT_INTEREST
               ,FC_CONDITION_INTEREST
               ,FD_OPERATION_DATE
               ,FD_APPLICATION_DATE
               ,FC_USER
               ,FD_CREATED_DATE
               ,FD_MODIFICATION_DATE)
         VALUES(
                PA_FI_LOAN_ID
               ,PA_FI_ADMIN_CENTER_ID
               ,PA_FI_PAYMENT_NUMBER_ID
               ,PA_FI_DAYS_ACUM_BY_TERM
               ,PA_FN_DAILY_INTEREST
               ,PA_FN_ACCRUED_INTEREST_BALANCE
               ,PA_FN_ACCRUED_INTEREST_LOAN
               ,PA_FN_PAYMENT_INTEREST
               ,PA_FC_CONDITION_INTEREST
               ,TO_DATE(PA_FD_OPERATION_DATE,CSL_DATE_FORMAT)
               ,TO_DATE(PA_FD_APPLICATION_DATE,CSL_DATE_FORMAT)
               ,USER
               ,SYSDATE
               ,SYSDATE
               );

      IF SQL%ROWCOUNT = CSL_0 THEN
         RAISE_APPLICATION_ERROR(CSL_20002, CSL_TA_LOAN_INTEREST || CSL_TA_LOAN_INTEREST);
      END IF;

      IF PA_COMMIT = CSL_1 THEN
         COMMIT;
      END IF;

      --EXCEPTION HANDLING
      EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        PA_STATUS_CODE := SQLCODE;
        PA_STATUS_MSG := SQLERRM || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;

        SC_CREDIT.SP_BATCH_ERROR_LOG(UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_SP)
                                    ,SQLCODE
                                    ,SQLERRM
                                    ,DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
                                    ,PA_FI_TRANSACTION
                                    ,CSL_LOANID || PA_FI_LOAN_ID || CSL_COMMA
                                       ||CSL_ADMINCENTERID ||PA_FI_ADMIN_CENTER_ID|| CSL_COMMA
                                       ||PA_FI_PAYMENT_NUMBER_ID|| CSL_COMMA
                                       ||PA_FI_DAYS_ACUM_BY_TERM|| CSL_COMMA
                                       ||PA_FD_APPLICATION_DATE|| CSL_COMMA
           );

     END SP_BTC_INS_DAILY_INTEREST;

/

GRANT EXECUTE ON SC_CREDIT.SP_BTC_INS_DAILY_INTEREST TO USRNCPCREDIT1
/
GRANT EXECUTE ON SC_CREDIT.SP_BTC_INS_DAILY_INTEREST TO USRBTCCREDIT1
/
