CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_SEL_CONCEPT_SIGN (
    PA_CUR_RESULT               OUT SC_CREDIT.PA_TYPES.TYP_CURSOR,
    PA_STATUS_CODE              OUT NUMBER,
    PA_STATUS_MSG               OUT VARCHAR2
    )
    IS
/*****************************************************************
  *PROJECT:      NCP
  *DESCRIPTION:  GET CATALOGS OF OPERATION TYPE AND SIGN OF THE OPERATION
  *CREATOR:      CARLOS EDUARDO_MARTINEZ CANTERO
  *CREATED DATE: NOV-22-2024
  *MODIFICATION: 2024-12-05 CARLOS EDUARDO MARTINEZ CANTERO_
*****************************************************************/
    CSL_ISSUE_CONCEPT_CODE CONSTANT              SIMPLE_INTEGER   := -20010;
    CSL_ISSUE_CONCEPT_MSG CONSTANT               VARCHAR2(100)    := 'FAILED TO IN CONCEPT_SIGN';
    CSG_SUCCESS_CODE CONSTANT SIMPLE_INTEGER := 0;
    CSG_SUCCESS_MSG CONSTANT VARCHAR2(15) := 'SUCCESS';

BEGIN
        OPEN PA_CUR_RESULT FOR
SELECT TCOP.FI_OPERATION_TYPE_ID,TCOPSIGN.FI_OPERATION_SIGN
FROM  SC_CREDIT.TC_OPERATION_TYPE TCOP
INNER JOIN
SC_CREDIT.TC_OPERATION_SIGN TCOPSIGN
ON
TCOP.FI_OPERATION_SIGN_ID=TCOPSIGN.FI_OPERATION_SIGN_ID WHERE TCOP.FI_STATUS=1 AND TCOPSIGN.FI_STATUS=1
ORDER BY TCOP.FI_OPERATION_TYPE_ID;


    PA_STATUS_CODE := CSG_SUCCESS_CODE;
    PA_STATUS_MSG := CSG_SUCCESS_MSG;
        EXCEPTION
   WHEN OTHERS THEN
    PA_STATUS_CODE := SQLCODE;
    PA_STATUS_MSG := SQLERRM;
   SC_CREDIT.SP_ERROR_LOG (CSL_ISSUE_CONCEPT_MSG, SQLCODE, SQLERRM,
                                   DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
                                   CSL_ISSUE_CONCEPT_CODE, 'SEL_CONCEPT_SIGN');
END SP_SEL_CONCEPT_SIGN;

/

GRANT EXECUTE ON SC_CREDIT.SP_SEL_CONCEPT_SIGN TO USRNCPCREDIT1
/
GRANT EXECUTE ON SC_CREDIT.SP_SEL_CONCEPT_SIGN TO USRPURPOSEWS
/
GRANT EXECUTE ON SC_CREDIT.SP_SEL_CONCEPT_SIGN TO USRCREDIT02
/
