CREATE OR REPLACE  TYPE SC_CREDIT.TYP_TAB_BTC_STATUS_PWO AS TABLE OF SC_CREDIT.TYP_REC_BTC_STATUS_PWO; 
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_STATUS_PWO TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_STATUS_PWO TO USRBTCCREDIT1;
