CREATE OR REPLACE  TYPE SC_CREDIT.TYP_REC_BTC_STATUS_PWO AS OBJECT (  FI_LOAN_ID                   NUMBER (15)                    , FI_ADMIN_CENTER_ID       NUMBER (8)                     , FN_PAY_OFF_AMOUNT        NUMBER (12,2)                  , FN_PWO_EXT_PAYMENT       NUMBER (12,2)                  , FN_AMOUNT_PAID           NUMBER (12,2)                  , FN_PWO_MIN_PAYMENT       NUMBER (12,2)                  , FI_ADD_EXTENSION         NUMBER (3)                     , FD_PWO_DATE       VARCHAR(50)
); 
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_STATUS_PWO TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_STATUS_PWO TO USRBTCCREDIT1;
