CREATE OR REPLACE  TYPE SC_CREDIT.TYP_TAB_BTC_LOAN AS TABLE OF SC_CREDIT.TYP_REC_BTC_LOAN; 
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_LOAN TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_LOAN TO USRBTCCREDIT1;
