CREATE OR REPLACE  FUNCTION SC_CREDIT.FN_GET_NEXT_LOAN_ID RETURN SC_CREDIT.TA_LOAN.FI_LOAN_ID%TYPE IS
/*************************************************************
  PROJECT    :  NCP
  DESCRIPTION:  FUNCTION TO GET THE NEXT LOAN_ID VALUE.
  CREATOR:      RICARDO GM.
  CREATED DATE: AGO-13-2024


         this is the vbersion 2
*************************************************************/
VL_NEXT_LOAN_ID SC_CREDIT.TA_LOAN.FI_LOAN_ID%TYPE;

BEGIN
    VL_NEXT_LOAN_ID := SC_CREDIT.SE_LOAN_ID.NEXTVAL;

    RETURN VL_NEXT_LOAN_ID;

EXCEPTION
    WHEN OTHERS THEN
        VL_NEXT_LOAN_ID := -1;
        SC_CREDIT.SP_ERROR_LOG('FN_GET_NEXT_LOAN_ID', SQLCODE, SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, '', '');
        RETURN VL_NEXT_LOAN_ID;


END FN_GET_NEXT_LOAN_ID;

/

GRANT EXECUTE ON SC_CREDIT.FN_GET_NEXT_LOAN_ID TO USRNCPCREDIT1
/
