CREATE OR REPLACE TYPE SC_CREDIT.TYP_TAB_BTC_BALANCE AS TABLE OF SC_CREDIT.TYP_REC_BTC_BALANCE; 
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_BALANCE TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_BALANCE TO USRBTCCREDIT1;
