CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_EXE_LOAN_BALANCE_INFO (
    PA_LOAN_ID                  SC_CREDIT.TA_PAYMENT_SCHEDULE.FI_LOAN_ID%TYPE,
    PA_CUR_LOAN                 OUT SYS_REFCURSOR,
    PA_CUR_BALANCE              OUT SYS_REFCURSOR,
    PA_STATUS_CODE              OUT NUMBER,
    PA_STATUS_MSG               OUT VARCHAR2)

  AS
  -- GLOBAL CONSTANTS
  CSG_0                     CONSTANT SIMPLE_INTEGER := 0;
  CSG_1                     CONSTANT SIMPLE_INTEGER := 1;
  CSG_ARROW                 CONSTANT VARCHAR2(5) := ' -> ';
  CSG_X                     CONSTANT VARCHAR2(5) := 'X';
  CSG_SUCCESS_CODE          CONSTANT SIMPLE_INTEGER := 0;
  CSG_SUCCESS_MSG           CONSTANT VARCHAR2(10) := 'SUCCESS';
  CSG_NO_DATA_FOUND_CODE    CONSTANT SIMPLE_INTEGER := -20204;
  CSG_NO_DATA_FOUND_MSG     CONSTANT VARCHAR2(50) := 'THE DATA DOES NOT EXIST';
  CSG_SP_EXE_LOAN_BALANCE_INFO  CONSTANT VARCHAR2(50) := 'SP_EXE_LOAN_BALANCE_INFO';
/*************************************************************
  PROJECT    :  NCP-OUTSTANDING BALANCE
  DESCRIPTION:  STORED PROCEDURE TO SELECT A LOAN
  CREATOR:      JOSE DE JESUS BRAVO AGUILAR.
  CREATED DATE: AGO-02-2024
  MODIFICATION: RICARDO HAZAEL GOMEZ ALVAREZ
  MODIFICATION DATE: OCT-09-2024
*************************************************************/
    VL_LOAN_ID                  SC_CREDIT.TA_LOAN.FI_LOAN_ID%TYPE;

    EXC_NO_DATA_FOUND           EXCEPTION;
    PRAGMA EXCEPTION_INIT (EXC_NO_DATA_FOUND, CSG_NO_DATA_FOUND_CODE);

  BEGIN
    PA_STATUS_CODE := CSG_SUCCESS_CODE;
    PA_STATUS_MSG := CSG_SUCCESS_MSG;

  SELECT COUNT(CSG_1)
  INTO VL_LOAN_ID
  FROM SC_CREDIT.TA_LOAN
  WHERE FI_LOAN_ID = PA_LOAN_ID;
  IF VL_LOAN_ID = CSG_0 THEN
    RAISE EXC_NO_DATA_FOUND;
  END IF;

  OPEN PA_CUR_LOAN  FOR
  SELECT
    FI_LOAN_ID,
    FI_COUNTRY_ID,
    FI_COMPANY_ID,
    FI_BUSINESS_UNIT_ID,
    FI_ADMIN_CENTER_ID,
    FI_ORIGINATION_CENTER_ID,
    FC_PLATFORM_ID,
    FC_SUB_PLATFORM_ID,
    FC_CUSTOMER_ID,
    FI_PRODUCT_ID,
    FN_PRINCIPAL_AMOUNT,
    FN_FINANCE_CHARGE_AMOUNT,
    FN_PRINCIPAL_BALANCE,
    FN_FINANCE_CHARGE_BALANCE,
    FN_ADDITIONAL_CHARGE_BALANCE,
    FD_ORIGINATION_DATE,
    FD_FIRST_PAYMENT,
    FD_DUE_DATE,
    FN_APR,
    FI_ADDITIONAL_STATUS,
    FI_CURRENT_BALANCE_SEQ,
    FN_INTEREST_RATE,
    FI_NUMBER_OF_PAYMENTS,
    FI_TERM_TYPE,
    FI_LOAN_STATUS_ID,
    FI_ACCRUED_TYPE_ID,
    FC_END_USER,
    FC_UUID_TRACKING,
    FC_IP_ADDRESS,
    FC_DEVICE
  FROM SC_CREDIT.TA_LOAN
  WHERE FI_LOAN_ID = PA_LOAN_ID;

  OPEN PA_CUR_BALANCE FOR
  SELECT
    LC.FC_LOAN_CONCEPT_DESC,
    LBD.FN_ITEM_AMOUNT
  FROM
    SC_CREDIT.TA_LOAN L
  LEFT OUTER JOIN SC_CREDIT.TA_LOAN_BALANCE LB
  ON L.FI_LOAN_ID = LB.FI_LOAN_ID
  AND L.FI_CURRENT_BALANCE_SEQ = LB.FI_BALANCE_SEQ
  LEFT OUTER JOIN SC_CREDIT.TA_LOAN_BALANCE_DETAIL LBD
  ON LB.FI_LOAN_BALANCE_ID = LBD.FI_LOAN_BALANCE_ID
  LEFT OUTER JOIN SC_CREDIT.TC_LOAN_CONCEPT LC
  ON LBD.FI_LOAN_CONCEPT_ID = LC.FI_LOAN_CONCEPT_ID
  WHERE
    L.FI_LOAN_ID = PA_LOAN_ID
    ORDER BY
    LB.FI_LOAN_BALANCE_ID ASC;

  EXCEPTION
  WHEN EXC_NO_DATA_FOUND THEN
    PA_STATUS_CODE := CSG_NO_DATA_FOUND_CODE;
    PA_STATUS_MSG := CSG_NO_DATA_FOUND_MSG || CSG_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
    OPEN PA_CUR_LOAN FOR SELECT
    NULL AS FI_COUNTRY_ID,
    NULL AS FI_COMPANY_ID,
    NULL AS FI_BUSINESS_UNIT_ID,
    NULL AS FI_ADMIN_CENTER_ID,
    NULL AS FI_LOAN_ID,
    NULL AS FI_ORIGINATION_CENTER_ID,
    NULL AS FC_PLATFORM_ID,
    NULL AS FC_SUB_PLATFORM_ID,
    NULL AS FC_CUSTOMER_ID,
    NULL AS FI_PRODUCT_ID,
    NULL AS FN_PRINCIPAL_AMOUNT,
    NULL AS FN_FINANCE_CHARGE_AMOUNT,
    NULL AS FN_PRINCIPAL_BALANCE,
    NULL AS FN_FINANCE_CHARGE_BALANCE,
    NULL AS FN_ADDITIONAL_CHARGE_BALANCE,
    NULL AS FD_ORIGINATION_DATE,
    NULL AS FD_FIRST_PAYMENT,
    NULL AS FD_DUE_DATE,
    NULL AS FN_APR,
    NULL AS FI_ADDITIONAL_STATUS,
    NULL AS FI_CURRENT_BALANCE_SEQ,
    NULL AS FN_INTEREST_RATE,
    NULL AS FI_NUMBER_OF_PAYMENTS,
    NULL AS FI_TERM_TYPE,
    NULL AS FI_LOAN_STATUS,
    NULL AS FI_ACCRUED_TYPE_ID,
    NULL AS FC_END_USER,
    NULL AS FC_UUID_TRACKING,
    NULL AS FC_IP_ADDRESS,
    NULL AS FC_DEVICE
   FROM DUAL WHERE CSG_1 = CSG_0;

     OPEN PA_CUR_BALANCE FOR SELECT
    NULL AS FC_CONCEPT,
    NULL AS FN_ITEM_AMOUNT
    FROM DUAL WHERE CSG_1 = CSG_0;

    SC_CREDIT.SP_ERROR_LOG(CSG_SP_EXE_LOAN_BALANCE_INFO, SQLCODE, SQLERRM,
      DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, CSG_X, CSG_X);

  WHEN OTHERS THEN
    PA_STATUS_CODE := SQLCODE;
    PA_STATUS_MSG := SQLERRM || CSG_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
    SC_CREDIT.SP_ERROR_LOG(CSG_SP_EXE_LOAN_BALANCE_INFO, SQLCODE, SQLERRM,
      DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, CSG_X, CSG_X);

  END SP_EXE_LOAN_BALANCE_INFO;

/

GRANT EXECUTE ON SC_CREDIT.SP_EXE_LOAN_BALANCE_INFO TO USRNCPCREDIT1
/
