CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_SEL_CONCEPT (
    PA_CUR_RESULT               OUT SC_CREDIT.PA_TYPES.TYP_CURSOR,
    PA_STATUS_CODE              OUT NUMBER,
    PA_STATUS_MSG               OUT VARCHAR2
    )
    IS

/*****************************************************************
  *PROJECT:      NCP
  *DESCRIPTION:  GET CATALOGS OF OPERATION TYPE AND SIGN OF THE OPERATION
  *CREATOR:      CARLOS EDUARDO_MARTINEZ CANTERO
  *CREATED DATE: NOV-22-2024
  *MODIFICATION: 2024-12-05 CARLOS EDUARDO MARTINEZ CANTERO
  V1.1: ADD STORED SC_CREDIT.SP_ERROR_LOG_
*****************************************************************/
        CSL_ISSUE_CONCEPT_CODE CONSTANT              SIMPLE_INTEGER   := -20010;
    CSL_ISSUE_CONCEPT_MSG CONSTANT               VARCHAR2(100)    := 'FAILED TO IN SP_SEL_CONCEPT';
    CSG_SUCCESS_CODE CONSTANT SIMPLE_INTEGER := 0;
    CSG_SUCCESS_MSG CONSTANT VARCHAR2(15) := 'SUCCESS';

BEGIN
        OPEN PA_CUR_RESULT FOR
SELECT FI_LOAN_CONCEPT_ID, FI_BALANCE_CATEGORY_ID  FROM SC_CREDIT.TC_LOAN_CONCEPT WHERE FI_STATUS=1;

    PA_STATUS_CODE := CSG_SUCCESS_CODE;
    PA_STATUS_MSG := CSG_SUCCESS_MSG;
        EXCEPTION
   WHEN OTHERS THEN
    PA_STATUS_CODE := SQLCODE;
    PA_STATUS_MSG := SQLERRM;
   SC_CREDIT.SP_ERROR_LOG (CSL_ISSUE_CONCEPT_MSG, SQLCODE, SQLERRM,
                                   DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
                                   CSL_ISSUE_CONCEPT_CODE, 'SP_SEL_CONCEPT_P');

END SP_SEL_CONCEPT;

/

GRANT EXECUTE ON SC_CREDIT.SP_SEL_CONCEPT TO USRNCPCREDIT1
/
GRANT EXECUTE ON SC_CREDIT.SP_SEL_CONCEPT TO USRPURPOSEWS
/
GRANT EXECUTE ON SC_CREDIT.SP_SEL_CONCEPT TO USRCREDIT02
/
