CREATE OR REPLACE  TYPE SC_CREDIT.TYP_REC_BTC_ERROR AS OBJECT (FC_ADMIN_CENTER_ID   NUMBER(8,0) ,FI_LOAN_ID           NUMBER(15,0) ,FC_PROCESS           VARCHAR2(80) ,FI_SQL_CODE          NUMBER(5) ,FC_SQL_ERRM          VARCHAR2(1000) ,FC_BACKTRACE         VARCHAR2(600) ,FD_ERROR             VARCHAR2(150) ,FI_TRANSACTION           NUMBER(33,0) ,FC_ADITIONAL             VARCHAR2(500 BYTE)
); 
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_ERROR TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_ERROR TO USRBTCCREDIT1;
