CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_SEL_LOAN_CONCEPT (
    PA_JSON_OBJECT OUT CLOB,
    PA_STATUS_CODE OUT NUMBER,
    PA_STATUS_MSG OUT VARCHAR2
)
    IS

    CSL_0 CONSTANT       SIMPLE_INTEGER := 0;
    CSL_1 CONSTANT       SIMPLE_INTEGER := 1;
    CSG_X CONSTANT       VARCHAR2(5)    := 'X';
    CSL_SP CONSTANT      SIMPLE_INTEGER := 1;
    CSL_ARROW CONSTANT   VARCHAR2(5)    := '->';
    CSL_SUCCESS CONSTANT VARCHAR2(8)    := 'SUCCESS';

BEGIN
    SELECT JSON_ARRAYAGG(
                   JSON_OBJECT(
                           'FI_LOAN_CONCEPT_ID' VALUE lc.FI_LOAN_CONCEPT_ID,
                           'FI_LOAN_CONCEPT_TYPE_ID' VALUE lc.FI_LOAN_CONCEPT_TYPE_ID
                   )
           )
    INTO PA_JSON_OBJECT
    FROM SC_CREDIT.TC_LOAN_CONCEPT LC;

    PA_STATUS_CODE := CSL_0;
    PA_STATUS_MSG := CSL_SUCCESS;

EXCEPTION
    WHEN OTHERS THEN
        PA_STATUS_CODE := SQLCODE;
        PA_STATUS_MSG := SQLERRM || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
        SC_CREDIT.SP_ERROR_LOG(
                        UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_SP)
            , SQLCODE
            , SQLERRM
            , DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
            , CSG_X
            , CSL_1
        );
END SP_SEL_LOAN_CONCEPT;

/

GRANT EXECUTE ON SC_CREDIT.SP_SEL_LOAN_CONCEPT TO USRNCPCREDIT1
/
