CREATE OR REPLACE  TYPE SC_CREDIT.TYP_REC_BTC_STATUS AS OBJECT (FI_LOAN_ID                  NUMBER(15,0) ,FI_ADMIN_CENTER_ID          NUMBER(8,0) ,FI_LOAN_OPERATION_ID      NUMBER(15,0) ,FI_LOAN_STATUS_ID             NUMBER(5,0) ,FI_LOAN_STATUS_OLD_ID     NUMBER(5,0) ,FI_TRIGGER_ID             NUMBER(3,0) ,FD_LOAN_STATUS_DATE         VARCHAR(50)
); 
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_STATUS TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_STATUS TO USRBTCCREDIT1;
