CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_UPD_LOAN_STATUS_DETAIL 
   (PA_LOAN_ID             IN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FI_LOAN_ID%TYPE,
    PA_ADMIN_CENTER_ID     IN SC_CREDIT.TA_LOAN_STATUS_DETAIL.FI_ADMIN_CENTER_ID%TYPE,
	PA_JSON_INPUT          IN VARCHAR2,
    PA_JSON_OUPUT          OUT VARCHAR2,
    PA_STATUS_CODE         OUT NUMBER,
    PA_STATUS_MESSAGE      OUT VARCHAR2)
IS
/**********************************************************************************************************************************************
PROJECT:            PURPOSE_LIFE_LOAN_CYCLE
DESCRIPTION:        STORED PROCEDURE THAT UPDATES SETTLED PAYMENTS
PRECONDITIONS:      IT MUST RECEIVE A JSON OBJECT
CREATED DATE:       15/12/2024
CREATOR:            AIXA SARMIENTO
MODIFICATION DATE:  15/01/2025
USER MODIFICATION:  AIXA SARMIENTO
***********************************************************************************************************************************************/
   CSL_0                    	CONSTANT SIMPLE_INTEGER := 0;			-- CONSTANT WITH VALUE EQUAL TO 0
   CSL_1                    	CONSTANT SIMPLE_INTEGER := 1;		    -- CONSTANT WITH VALUE EQUAL TO 1
   CSL_3                    	CONSTANT SIMPLE_INTEGER := 3;		    -- CONSTANT WITH VALUE EQUAL TO 1
   CSL_4                        CONSTANT SIMPLE_INTEGER := 4;           -- CONSTANT WITH VALUE EQUAL TO 4
   CSL_MSG_SUCCESS          	CONSTANT VARCHAR2(20)   := 'SUCCESS';	-- MESSAGE SUCCESS
   CSL_ARROW                    CONSTANT VARCHAR2(5)    := '-->';		-- AESTHETICS SIGN
   VL_FINAL_DATE                VARCHAR2(25);
   VL_PAYMENT_NUMBER_ID         NUMBER(5)               := 0;
   VL_DATE_FORMAT               VARCHAR2(12)             := 'DD/MM/YYYY';
   VL_DATE_DEFAULT              VARCHAR2(25)             := '01/01/1991';
   VL_SPACE                     VARCHAR2(5)              := ' ';
   VL_DATA_OUT                  VARCHAR2(4000)           :=  PA_LOAN_ID || VL_SPACE || PA_ADMIN_CENTER_ID || VL_SPACE || PA_JSON_INPUT;

BEGIN

--- PAYMENTS ARE UPDATED IN TA_LOAN_STATUS_DETAIL

      UPDATE SC_CREDIT.TA_LOAN_STATUS_DETAIL T
         SET T.FI_ON_OFF = CSL_0  -- OFF
       WHERE FI_LOAN_ID = PA_LOAN_ID
		AND FI_ADMIN_CENTER_ID = PA_ADMIN_CENTER_ID
		AND FI_ON_OFF = CSL_1 -- RECORDS ON
		AND FI_LOAN_STATUS_ID = CSL_3
		AND FI_ACTION_DETAIL_ID = CSL_3
		AND T.FI_PAYMENT_NUMBER_ID IN (
						  SELECT FI_PAYMENT_NUMBER_ID
							FROM JSON_TABLE(PA_JSON_INPUT, '$.payment.schedules[*]'
                                            COLUMNS(
                                                     FI_PAYMENT_NUMBER_ID        NUMBER(15)    PATH   '$.paymentNumber'
                                                    )
                             ));
   COMMIT;


PA_STATUS_CODE    :=  CSL_0;
PA_STATUS_MESSAGE := CSL_MSG_SUCCESS;

PA_JSON_OUPUT 	 := JSON_OBJECT('PA_STATUS_CODE'    VALUE PA_STATUS_CODE,
                                    'PA_STATUS_MESSAGE' VALUE PA_STATUS_MESSAGE
									);


EXCEPTION

  WHEN NO_DATA_FOUND THEN
      ROLLBACK;

         PA_STATUS_CODE    := 101;                     -- NO UPDATED CODE
         PA_STATUS_MESSAGE := 'No data updated';       -- NO LOAN MESSAGE
         PA_JSON_OUPUT     := JSON_OBJECT('PA_STATUS_CODE'   VALUE SQLCODE,
									      'PA_STATUS_MESSAGE' VALUE SQLERRM  || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
									      FORMAT JSON);

		 SC_CREDIT.SP_ERROR_LOG('SP_UPD_LOAN_STATUS_DETAIL', SQLCODE, SQLERRM,
         DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, PA_LOAN_ID , VL_DATA_OUT );

   WHEN OTHERS THEN
      ROLLBACK;

         PA_STATUS_CODE    := 100;                               -- NO DATA FOUND CODE
         PA_STATUS_MESSAGE := 'No update/insertion done';        -- NO DATA FOUND MESSAGE
         PA_JSON_OUPUT     := JSON_OBJECT('PA_STATUS_CODE'   VALUE SQLCODE,
									      'PA_STATUS_MESSAGE' VALUE SQLERRM  || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
									      FORMAT JSON);

         SC_CREDIT.SP_ERROR_LOG('SP_UPD_LOAN_STATUS_DETAIL', SQLCODE, SQLERRM,
         DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, PA_LOAN_ID , VL_DATA_OUT );

END SP_UPD_LOAN_STATUS_DETAIL;

/

GRANT EXECUTE ON SC_CREDIT.SP_UPD_LOAN_STATUS_DETAIL TO USRNCPCREDIT1
/
