CREATE OR REPLACE  TYPE SC_CREDIT.TYP_REC_BTC_OPERATION AS OBJECT ( FI_LOAN_OPERATION_ID     NUMBER(15), FI_COUNTRY_ID            NUMBER(3), FI_COMPANY_ID            NUMBER(3), FI_BUSINESS_UNIT_ID      NUMBER(3), FI_LOAN_ID               NUMBER(15), FI_ADMIN_CENTER_ID       NUMBER(8,0), FI_OPERATION_TYPE_ID     NUMBER(5), FN_OPERATION_AMOUNT      NUMBER(12, 2), FC_APPLICATION_DATE      VARCHAR2(50), FC_OPERATION_DATE        VARCHAR2(50), FI_STATUS                NUMBER(3), FC_END_USER              VARCHAR2(10), FC_UUID_TRACKING         VARCHAR2(36)
); 
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_OPERATION TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_OPERATION TO USRBTCCREDIT1;
