CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_SEL_OPERATION_REF_PAYMENT (
    PA_REFERENCE_ID     IN  SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT.FC_REFERENCE_ID%TYPE,
    PA_OPERATION_REF_ID OUT SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT.FI_OPERATION_REF_ID%TYPE,
    PA_STATUS_CODE      OUT NUMBER,
    PA_STATUS_MSG       OUT VARCHAR2
)
IS
 /* *************************************************************************
 * PROJECT: CORE LOAN
 * DESCRIPTION: PROCEDURE FOR GETTING PA_OPERATION_REF_ID OF AN
 *              OPERATION TO BE CLEARED.
 * PRECONDITIONS: PRE-EXISTING LOANS AND OPERATIONS
 * CREATED DATE: 07/01/2025
 * CREATOR: GILBERTO CHAVEZ MUNOZ
 ****************************************************************************/
  CSL_0             CONSTANT SIMPLE_INTEGER := 0;
  CSL_1             CONSTANT SIMPLE_INTEGER := 1;
  CSL_204           CONSTANT SIMPLE_INTEGER := 204;
  CSL_SP            CONSTANT SIMPLE_INTEGER := 1;
  CSL_ARROW         CONSTANT VARCHAR2(5)  := '->';
  CSL_JSON          CONSTANT VARCHAR2(5)  := NULL;
  CSL_SUCCESS       CONSTANT VARCHAR2(8)  := 'SUCCESS';
  CSL_NO_DATA_FOUND CONSTANT VARCHAR2(20) := 'NO REFERENCE FOUND';
BEGIN
  PA_STATUS_CODE := CSL_0;
  PA_STATUS_MSG  := CSL_SUCCESS;

SELECT ORP.FI_OPERATION_REF_ID
INTO   PA_OPERATION_REF_ID
FROM   SC_CREDIT.TA_LOAN_OPERATION_REF_PAYMENT ORP
WHERE  ORP.FC_REFERENCE_ID = PA_REFERENCE_ID;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    PA_STATUS_CODE := CSL_204;
    PA_STATUS_MSG  := CSL_NO_DATA_FOUND;
WHEN OTHERS THEN
    PA_STATUS_CODE := SQLCODE;
    PA_STATUS_MSG  := SQLERRM || CSL_ARROW || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
    SC_CREDIT.SP_ERROR_LOG(
       UTL_CALL_STACK.SUBPROGRAM(CSL_1)(CSL_SP)
       ,SQLCODE
       ,SQLERRM
       ,DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
       ,NULL
       ,CSL_JSON
       );
END SP_SEL_OPERATION_REF_PAYMENT;

/

GRANT EXECUTE ON SC_CREDIT.SP_SEL_OPERATION_REF_PAYMENT TO USRNCPCREDIT1
/
