CREATE OR REPLACE  FUNCTION SC_CREDIT.FN_GET_NEXT_LOAN_OPERATION_ID RETURN SC_CREDIT.TA_LOAN_OPERATION.FI_LOAN_OPERATION_ID%TYPE AS
/*************************************************************
  PROJECT    :  NCP
  DESCRIPTION:  FUNCTION TO GET THE NEXT LOAN OPERATION ID VALUE
  CREATOR:      RICARDO GM.
  CREATED DATE: 2024-10-10
*************************************************************/

BEGIN
 RETURN SC_CREDIT.SE_LOAN_OPERATION_ID.NEXTVAL;

EXCEPTION
    WHEN OTHERS THEN

        SC_CREDIT.SP_ERROR_LOG('FN_GET_NEXT_LOAN_ID', SQLCODE, SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, '', '');
        RETURN -1;



END FN_GET_NEXT_LOAN_OPERATION_ID;

/

GRANT EXECUTE ON SC_CREDIT.FN_GET_NEXT_LOAN_OPERATION_ID TO USRNCPCREDIT1
/
