CREATE OR REPLACE  PROCEDURE SC_CREDIT.SP_SYNC_LOAN_STATUS (
    PA_SYNC_JSON   		CLOB,
    PA_UPDATED_ROWS	OUT NUMBER,
    PA_STATUS_CODE	OUT NUMBER,
    PA_STATUS_MSG	OUT VARCHAR2
  ) IS
/* **************************************************************
* PROJECT: NCP
* DESCRIPTION: CATALOG SYNCHONIZATION TC_LOAN_STATUS
* CREATED DATE: 2025/01/09
* CREATOR: CESAR CORTES
* MODIFICATION DATE: 2025/01/09
************************************************************** */
  CSL_0 CONSTANT SIMPLE_INTEGER := 0;
BEGIN
  PA_STATUS_CODE := CSL_0;
  PA_STATUS_MSG := 'OK';
  PA_UPDATED_ROWS  := CSL_0;

  MERGE INTO SC_CREDIT.TC_LOAN_STATUS A
  USING (
    SELECT
      *
    FROM
      JSON_TABLE ( PA_SYNC_JSON, '$.loanStatus[*]'
        COLUMNS (
          ID NUMBER PATH '$.id',
          DESCRIPTION VARCHAR2 ( 50 ) PATH '$.description',
          ACRONYM VARCHAR2 ( 50 ) PATH '$.acronym',
          STATUS NUMBER PATH '$.status',
          USER_NAME VARCHAR2 ( 50 ) PATH '$.user',
          CREATED_DATE TIMESTAMP PATH '$.createdDate',
          MODIFICATION_DATE TIMESTAMP PATH '$.modificationDate'
        )
      )
  ) B ON ( A.FI_LOAN_STATUS_ID = B.ID )
  WHEN MATCHED THEN UPDATE
  SET A.FC_LOAN_STATUS_DESC = B.DESCRIPTION,
	  A.FC_ACRONYM 	 =B.ACRONYM,
      A.FI_STATUS = B.STATUS,
      A.FC_USER = B.USER_NAME,
      A.FD_MODIFICATION_DATE = CAST(B.MODIFICATION_DATE AS DATE)
  WHEN NOT MATCHED THEN
  INSERT (
    FI_LOAN_STATUS_ID,
    FC_LOAN_STATUS_DESC,
    FC_ACRONYM,
    FI_STATUS,
    FC_USER,
    FD_CREATED_DATE,
    FD_MODIFICATION_DATE )
  VALUES
    ( B.ID,
      B.DESCRIPTION,
      B.ACRONYM,
      B.STATUS,
      B.USER_NAME,
      B.CREATED_DATE,
      B.MODIFICATION_DATE );

      PA_UPDATED_ROWS := SQL%ROWCOUNT;

  COMMIT;

  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      PA_STATUS_CODE := SQLCODE;
    PA_STATUS_MSG  := SQLERRM;
      SC_CREDIT.SP_ERROR_LOG('SP_SYNC_LOAN_STATUS', SQLCODE, SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, NULL,'');

  END SP_SYNC_LOAN_STATUS;

/

GRANT EXECUTE ON SC_CREDIT.SP_SYNC_LOAN_STATUS TO USRPURPOSEWS
/
GRANT EXECUTE ON SC_CREDIT.SP_SYNC_LOAN_STATUS TO USRNCPCREDIT1
/
