CREATE OR REPLACE  TYPE SC_CREDIT.TYP_REC_BTC_LOAN AS OBJECT (FI_ADMIN_CENTER_ID                NUMBER(8,0) ,FI_LOAN_ID                        NUMBER(15,0) ,FN_PRINCIPAL_BALANCE              NUMBER(12,2) ,FN_FINANCE_CHARGE_BALANCE         NUMBER(12,2) ,FN_ADDITIONAL_CHARGE_BALANCE      NUMBER(12,2) ,FI_ADDITIONAL_STATUS              NUMBER(5,0) ,FI_CURRENT_BALANCE_SEQ            NUMBER(5,0) ,FI_LOAN_STATUS_ID                 NUMBER(5,0) ,FC_LOAN_STATUS_DATE               VARCHAR(50) ,FI_TRANSACTION                    NUMBER(15)
); 
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_LOAN TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_REC_BTC_LOAN TO USRBTCCREDIT1;
