CREATE OR REPLACE  TYPE SC_CREDIT.TYP_TAB_BTC_OPERATION AS TABLE OF SC_CREDIT.TYP_REC_BTC_OPERATION; 
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_OPERATION TO USRNCPCREDIT1;
GRANT EXECUTE ON SC_CREDIT.TYP_TAB_BTC_OPERATION TO USRBTCCREDIT1;
